Repository lanl/Draco, pull requests merged in 2018-12, with the labels that each got.

#540 Enhance autodoc features.
  autodoc/CMakeLists.txt
  config/autodoc_macros.cmake
  config/doxygen_config.in
  src/ds++/Safe_Divide.hh
Labels: enhancement

#541 Update regression environment to fix script-update bug.
  regression/covclass_cmake.cfg
  regression/draco_regression_macros.cmake
  regression/update_regression_scripts.sh
Labels: bug

#530 Compton with average energy deposition
  environment/bashrc/.bashrc_toss3
  environment/bashrc/.bashrc_tt
  regression/ccscs-regress.msub
  regression/cts1-regress.msub
  regression/tt-regress.msub
  src/compton/Compton.cc
  src/compton/Compton.hh
  src/compton/config.h.in
  src/compton/test/lagrange_csk_ascii.compton
  src/compton/test/llnl_ascii.compton_erec
  src/compton/test/llnl_ascii.compton_sigc
  src/compton/test/tCompton.cc
Labels: enhancement, ready

#543 Updates to the LANL HPC release scripts.
  regression/scripts/README
  regression/scripts/cray-env.sh
  regression/scripts/cts-env.sh
  regression/scripts/release_bgq.msub
  regression/scripts/release_bgq.sh
  regression/scripts/release_cray.sh
  regression/scripts/release_cts.sh
  regression/scripts/release_darwin.msub
  regression/scripts/release_toss.sh
Labels: dev-env, enhancement

#542 Add compton to VS2017 regressions.
  config/FindCOMPTON.cmake
  config/vendor_libraries.cmake
  src/compton/test/tCompton.cc
Labels: enhancement, ready

#544 Compton bugfix
  config/FindCOMPTON.cmake
  environment/bashrc/.bashrc_toss3
  environment/bashrc/.bashrc_tt
  regression/ccscs-regress.msub
  regression/cts1-regress.msub
  regression/tt-regress.msub
  src/compton/Compton.cc
  src/compton/test/tCompton.cc
Labels: bug, ready

#547 Misc updates to prepare for next release
  config/autodoc_macros.cmake
  config/doxygen_config.in
  environment/bashrc/.bashrc_tt
  environment/elisp/draco-config-modes.el
  regression/ccscs2-crontab
  regression/cts1-regress.msub
  src/c4/ParallelUnitTest.hh
  src/c4/ParallelUnitTest.i.hh
  src/ds++/Assert.hh
  src/ds++/ScalarUnitTest.i.hh
Labels: bug, enhancement

#552 Added missing header.
  src/diagnostics/test/tstTiming.cc
Labels: bug

#548 Enable xthi and ythi builds/tests for Visual Studio.
  .clang-format
  src/c4/CMakeLists.txt
  src/c4/bin/CMakeLists.txt
  src/c4/bin/xthi.cc
  src/c4/bin/xthi.hh
  src/c4/bin/ythi.cc
  src/ds++/SystemCall.cc
  src/ds++/config.h.in
  src/ds++/path.hh
Labels: enhancement

#549 Add boilerplate base for Class_Parse_Table
  src/parser/Class_Parse_Table.hh
  src/parser/test/tstClass_Parser.cc
  src/parser/utilities.hh
Labels: enhancement
