Repository lanl/Draco, pull requests merged in 2018-08, with the labels that each got.

#443 More extensions to support 64-bit builds under VS 2017.
  config/CMakeAddFortranSubdirectory.cmake
  config/compilerEnv.cmake
  config/windows-cl.cmake
  regression/draco_regression_macros.cmake
  regression/update_regression_dir.bat
  regression/win32-regress.bat
  regression/win32-regression-master.bat
Labels: bug, needs-review

#442 Move default to Intel 18
  config/compilerEnv.cmake
  environment/bashrc/.bashrc_toss22
  environment/bashrc/.bashrc_toss3
  environment/bashrc/.bashrc_tt
  regression/cts1-regress.msub
  regression/sn-crontab
  regression/tt-regress.msub
Labels: dev-env, needs-review

#444 Include lapack_wrap for Linux+LLVM and Windows builds (if lapack is found)
  config/CMakeAddFortranSubdirectory.cmake
  config/component_macros.cmake
  config/vendor_libraries.cmake
  src/CMakeLists.txt
  src/lapack_wrap/CMakeLists.txt
  src/lapack_wrap/test/CMakeLists.txt
  src/lapack_wrap/test/tstBlas_Level_1.cc
Labels: enhancement

#445 More build system tweaks implemented while porting to VS2017 Win64.
  config/compilerEnv.cmake
  environment/git/pre-commit-clang-format
  regression/draco_regression_macros.cmake
  regression/win32-regress.bat
  src/FortranChecks/CMakeLists.txt
  src/FortranChecks/f90sub/CMakeLists.txt
  src/VendorChecks/CMakeLists.txt
Labels: bug, enhancement, needs-review

#447 WIP: Begin requiring cmake-3.11+.
  CMakeLists.txt
  config/ApplicationUnitTest.cmake
  config/application_unit_test.py
  config/component_macros.cmake
  config/draco-config-install.cmake.in
  config/setupMPI.cmake
  environment/bashrc/.bashrc_darwin_fe
  environment/bashrc/.bashrc_toss22
  environment/bashrc/.bashrc_toss3
  environment/bashrc/.bashrc_tt
  environment/git/pre-commit
  regression/cts1-regress.msub
  regression/darwin-regress.msub
  regression/scripts/release_darwin.sh
  regression/sn-crontab
  regression/tt-regress.msub
  src/CMakeLists.txt
  src/c4/config.h.in
  src/diagnostics/draco_info.cc
Labels: dev-env, needs-review

#451 Update mesh and X3D parser in src/mesh/ directory.
  src/mesh/Draco_Mesh.cc
  src/mesh/Draco_Mesh.hh
  src/mesh/X3D_Draco_Mesh_Reader.cc
  src/mesh/test/tstDraco_Mesh.cc
  src/mesh/test/tstX3D_Draco_Mesh_Reader.cc
Labels: enhancement, needs-review

#452 Add support for 5 static analysis tools.
  CMakeLists.txt
  config/compilerEnv.cmake
  config/unix-clang.cmake
  config/windows-cl.cmake
Labels: enhancement, needs-review, ready

#455 Update ds++/config.h to provide draco_isKNL.
  src/ds++/CMakeLists.txt
  src/ds++/config.h.in
  src/rng/Counter_RNG.hh
  src/rng/config.h.in
  src/rng/test/CMakeLists.txt
  src/rng/test/kat_cpp.cpp
  src/rng/test/time_initkeyctr.h
  src/rng/test/ut_Engine.cpp
  src/rng/test/ut_uniform.cpp
  src/rng/test/util_expandtpl.h
  src/rng/uniform.hpp
Labels: enhancement, ready

#456 Small tweaks and fixes.
  .travis.yml
  config/FindCOMPTON.cmake
  config/component_macros.cmake
  config/vendor_libraries.cmake
  environment/bashrc/.bashrc
  environment/bashrc/.bashrc_slurm
  environment/bashrc/.bashrc_tt
  regression/ccscs2-crontab
  regression/travis-run-tests.sh
Labels: dev-env, enhancement, needs-review, ready

#457 Prefetch
  src/ds++/Prefetch.hh
  src/ds++/test/tstPrefetch.cc
Labels: enhancement

#458 Fix ambiguous type conversion issue when compiling on a MAC
  src/viz/Ensight_Translator.i.hh
Labels: needs-review
