Repository lanl/Draco, pull requests merged in 2018-03, with the labels that each got.

#373 Add a check_all function to the UnitTest class tree.
  src/c4/ParallelUnitTest.cc
  src/c4/ParallelUnitTest.hh
  src/c4/test/tstParallelUnitTest.cc
  src/ds++/UnitTest.hh
  src/ds++/test/tstScalarUnitTest.cc
Labels: enhancement, ready

#374 Add slurm function to print total cpu-hr usage.
  environment/bashrc/.bashrc_slurm
Labels: dev-env, ready

#370 Improve error diagnostics for Parse_Table.
  src/parser/Console_Token_Stream.cc
  src/parser/Console_Token_Stream.hh
  src/parser/File_Token_Stream.cc
  src/parser/File_Token_Stream.hh
  src/parser/Parallel_File_Token_Stream.cc
  src/parser/Parallel_File_Token_Stream.hh
  src/parser/Parse_Table.cc
  src/parser/Parse_Table.hh
  src/parser/String_Token_Stream.cc
  src/parser/String_Token_Stream.hh
  src/parser/Token_Stream.hh
  src/parser/test/tstConsole_Token_Stream.cc
  src/parser/test/tstFile_Token_Stream.cc
  src/parser/test/tstParallel_File_Token_Stream.cc
  src/parser/test/tstParse_Table.cc
  src/parser/test/tstString_Token_Stream.cc
Labels: enhancement, needs-review

#371 Tweak some code for efficiency.
  src/cdi/CDI.hh
  src/quadrature/Ordinate_Set.cc
  src/quadrature/Quadrature.cc
Labels: enhancement, ready

#369 Move special Xcode/VS code into add_component_library.
  config/component_macros.cmake
  config/generate_dll_declspec.cmake
  src/RTT_Format_Reader/CMakeLists.txt
  src/c4/CMakeLists.txt
  src/cdi/CMakeLists.txt
  src/cdi_analytic/CMakeLists.txt
  src/cdi_eospac/CMakeLists.txt
  src/cdi_ipcress/CMakeLists.txt
  src/compton/CMakeLists.txt
  src/device/GPU_Device.cmake
  src/diagnostics/qt/CMakeLists.txt
  src/ds++/CMakeLists.txt
  src/fit/CMakeLists.txt
  src/lapack_wrap/CMakeLists.txt
  src/linear/CMakeLists.txt
  src/memory/CMakeLists.txt
  src/meshReaders/CMakeLists.txt
  src/mesh_element/CMakeLists.txt
  src/min/CMakeLists.txt
  src/norms/CMakeLists.txt
  src/ode/CMakeLists.txt
  src/parser/CMakeLists.txt
  src/plot2D/CMakeLists.txt
  src/quadrature/CMakeLists.txt
  src/rng/CMakeLists.txt
  src/rng/Counter_RNG.hh
  src/rng/config.h.in
  src/rng/test/kat_cpp.cpp
  src/rng/test/time_initkeyctr.h
  src/rng/test/ut_Engine.cpp
  src/rng/test/ut_Engine.hh
  src/rng/test/ut_uniform.cpp
  src/rng/test/util_expandtpl.h
  src/rng/uniform.hpp
  src/roots/CMakeLists.txt
  src/special_functions/CMakeLists.txt
  src/timestep/CMakeLists.txt
  src/units/CMakeLists.txt
  src/viz/CMakeLists.txt
Labels: enhancement, needs-review, needs-work

#368 Update environments to support Darwin KNL and Power8 nodes.
  config/platform_checks.cmake
  config/query_fma.cc
  environment/bashrc/.bashrc_darwin_fe
Labels: bug, dev-env, needs-review

#377 WIP: Try to fix pip upgrade failure in Travis.
  .travis.yml
Labels: bug

#376 Merge Draco-6_24_0 back to develop
  CMakeLists.txt
  ChangeLog
  regression/scripts/release_cray.sh
  regression/scripts/release_toss.sh
  src/ds++/Release.cc
Labels: enhancement, ready

#375 Use features of cmake-3.9 to set project version.
  CMakeLists.txt
  autodoc/CMakeLists.txt
  config/component_macros.cmake
  config/draco-config-install.cmake.in
  config/dracoVersion.cmake
  environment/bashrc/.bashrc
  regression/scripts/release_bgq.sh
  regression/scripts/release_cray.sh
  regression/scripts/release_darwin.sh
  regression/scripts/release_toss.sh
  src/CMakeLists.txt
  src/FortranChecks/autodoc/FortranChecks.dcc.in
  src/RTT_Format_Reader/autodoc/RTT_Format_Reader.dcc.in
  src/c4/autodoc/c4.dcc.in
  src/cdi/autodoc/cdi.dcc.in
  src/cdi_analytic/autodoc/cdi_analytic.dcc.in
  src/cdi_eospac/autodoc/cdi_eospac.dcc.in
  src/cdi_ipcress/autodoc/cdi_ipcress.dcc.in
  src/device/autodoc/device.dcc
  src/diagnostics/autodoc/diagnostics.dcc.in
  src/ds++/Release.cc
  src/ds++/autodoc/ds++.dcc.in
  src/ds++/config.h.in
  src/lapack_wrap/autodoc/lapack_wrap.dcc.in
  src/memory/autodoc/diagnostics.dcc.in
  src/meshReaders/autodoc/meshReaders.dcc.in
  src/mesh_element/autodoc/mesh_element.dcc.in
  src/norms/autodoc/norms.dcc.in
  src/parser/autodoc/parser.dcc.in
  src/quadrature/autodoc/quadrature.dcc.in
  src/rng/autodoc/rng.dcc.in
  src/shared_lib/autodoc/shared_lib.dcc.in
  src/special_functions/autodoc/special_functions.dcc.in
  src/timestep/autodoc/timestep.dcc.in
  src/units/autodoc/units.dcc.in
  src/viz/autodoc/viz.dcc.in
Labels: dev-env, enhancement

#378 Add a runtime_check function to rtt_c4
  src/diagnostics/runtime_check.cc
  src/diagnostics/runtime_check.hh
  src/diagnostics/test/tstruntime_error.cc
Labels: enhancement

#379 Fix an MPI detection issue.
  config/setupMPI.cmake
  regression/Draco_Linux64.cmake
  regression/draco_regression_macros.cmake
  regression/update_regression_dir.bat
  regression/win32-regress.bat
  regression/win32-regression-master.bat
Labels: bug
