Repository lanl/Draco, pull requests merged in 2018-09, with the labels that each got.

#461 Clean up build warnings reported by VS and fix some regression scripts
  regression/draco_regression_macros.cmake
  regression/win32-regression-master.bat
  src/VendorChecks/test/tstParmetis.cc
  src/ds++/test/do_exception.cc
Labels: bug, needs-review

#462 A few misc. updates.
  config/unix-crayCC.cmake
  environment/bashrc/.bashrc_slurm
  regression/Dockerfile
  src/RTT_Format_Reader/RTT_Mesh_Reader.hh
  src/mesh_element/Element_Definition.cc
  src/mesh_element/Element_Definition.hh
  src/mesh_element/Geometry.hh
Labels: enhancement

#463 Provide helper scripts for checking code style.
  .gitignore
  environment/elisp/format-f90.el
  environment/elisp/format-f90.sh
  environment/vim/.vimrc
  src/CMakeLists.txt
  src/ds++/DracoStrings.cc
  src/ds++/DracoStrings.hh
  src/ds++/test/tstDracoStrings.cc
  src/ds++/test/tstPrefetch.cc
  src/mesh/CMakeLists.txt
Labels: dev-env, needs-review, ready

#464 Fix a compatibility issue related to Python3
  config/application_unit_test.py
  config/unix-g++.cmake
  config/unix-ifort.cmake
  config/windows-cl.cmake
  environment/elisp/format-f90.el
Labels: bug, enhancement, needs-review

#468 Improve mesh_element and norms code coverage
  src/mesh_element/Element_Definition.cc
  src/mesh_element/Element_Definition.hh
  src/norms/Norms_Index.hh
  src/norms/Norms_Index.t.cc
  src/norms/Norms_Index.t.hh
Labels: enhancement, needs-review

#473 Improve quadrature coverage by adding tests or removing features.
  src/quadrature/Galerkin_Ordinate_Space.cc
  src/quadrature/Galerkin_Ordinate_Space.hh
  src/quadrature/Ordinate_Set_Mapper.hh
  src/quadrature/Ordinate_Space.cc
  src/quadrature/Ordinate_Space.hh
  src/quadrature/QIM.hh
  src/quadrature/QIM__Parser.cc
  src/quadrature/test/quadrature_test.hh
  src/quadrature/test/tstDouble_Gauss.cc
Labels: enhancement, needs-review

#474 Attempt to fix missing codecov reports.
  .codecov.yml
  .travis.yml
  config/vendor_libraries.cmake
  regression/travis-run-tests.sh
Labels: bug

#476 Add support for Grizzly.
  environment/bashrc/.bashrc
  regression/cts1-job-launch.sh
  regression/cts1-options.sh
  regression/regression-master.sh
Labels: dev-env, needs-review

#477 Restore the prune function to Ordinate_Space.
  src/quadrature/Galerkin_Ordinate_Space.hh
  src/quadrature/Ordinate_Space.cc
  src/quadrature/Ordinate_Space.hh
  src/quadrature/test/quadrature_test.cc
Labels: enhancement, ready

#478 Extend rtt_viz::Ensight_Translator's ensight_dump function.
  src/ds++/UnitTest.hh
  src/units/MathConstants.hh
  src/viz/Ensight_Translator.cc
  src/viz/Ensight_Translator.i.hh
  src/viz/test/tstEnsight_Translator.cc
Labels: enhancement, needs-review, ready

#466 Improve ds++ code coverage by adding tests or removing features
  src/ds++/Assert.cc
  src/ds++/Assert.hh
  src/ds++/Packing_Utils.hh
  src/ds++/UnitTest.hh
  src/ds++/test/tstPacking_Utils.cc
  src/ds++/test/tstScalarUnitTest.cc
Labels: enhancement, ready

#480 Fix some issues in ofpstream that were causing McGrid to fail.
  src/c4/Compare.cc
  src/c4/ofpstream.cc
  src/c4/opstream.cc
  src/c4/opstream.hh
  src/ds++/DracoStrings.hh
Labels: bug, needs-review

#483 Fix GSL discovery.
  config/vendor_libraries.cmake
Labels: bug, enhancement

#482 Fix broken draco_info tool.
  src/diagnostics/draco_info.cc
  src/ds++/CMakeLists.txt
  src/ds++/Release.cc
  src/ds++/Release.hh
  src/ds++/bin/CMakeLists.txt
  src/ds++/config.h.in
  src/ds++/test/tstPacking_Utils.cc
  src/quadrature/test/tstTri_Chebyshev_Legendre.cc
Labels: bug, needs-review

#467 Improve c4 code coverage by adding tests or removing features
  src/c4/Global_Timer.hh
  src/c4/Processor_Group.cc
  src/c4/Processor_Group.hh
  src/c4/Processor_Group.i.hh
  src/c4/Timer.hh
  src/c4/test/CMakeLists.txt
  src/c4/test/tstGlobalTimer.cc
  src/c4/test/tstProcessor_Group.cc
  src/c4/test/tstTime.cc
Labels: dev-env, needs-review

#485 Avoid compiling for AVX2 instructions on older hardware.
  appveyor.yml
  config/platform_checks.cmake
  config/query_fma.cc
  config/windows-cl.cmake
  environment/bashrc/.bashrc_slurm
  environment/bashrc/.bashrc_tt
  src/FortranChecks/f90sub/drel.f90
Labels: bug, enhancement

#486 Improve coverage in cdi_ipcress (and other cleanup)
  appveyor.yml
  config/ApplicationUnitTest.cmake
  config/application_unit_test.py
  src/cdi_ipcress/IpcressDataTable.cc
  src/cdi_ipcress/IpcressDataTable.hh
  src/cdi_ipcress/IpcressFile.cc
  src/cdi_ipcress/IpcressFile.hh
  src/cdi_ipcress/IpcressInterpreter.cc
  src/cdi_ipcress/IpcressOdfmgOpacity.hh
  src/cdi_ipcress/test/CMakeLists.txt
  src/cdi_ipcress/test/Ipcress_Interpreter-Al_BeCu.ipcress.gold
  src/cdi_ipcress/test/ReadOdfIpcressFile.cc
  src/cdi_ipcress/test/tIpcressFile.cc
  src/cdi_ipcress/test/tIpcressOdfmgOpacity.cc
  src/cdi_ipcress/test/tIpcressOpacity.cc
  src/cdi_ipcress/test/tIpcressWithCDI.cc
  src/cdi_ipcress/test/tIpcress_Interpreter.cmake
  src/cdi_ipcress/test/tIpcress_Interpreter.py
Labels: enhancement
