Repository lanl/Draco, pull requests merged in 2018-07, with the labels that each got.

#425 Try to Re-enable a baseline (no MPI) Travis build.
  .travis-install-dependencies.sh
  .travis-run-tests.sh
  .travis.yml
  CMakeLists.txt
  config/component_macros.cmake
  config/unix-g++.cmake
  regression/ccscs2-crontab
  src/CMakeLists.txt
  src/rng/Counter_RNG.hh
  src/rng/Random_Inline.hh
  src/rng/test/CMakeLists.txt
Labels: bug, enhancement, needs-review, ready

#431 Alternate solution for Processor_Group definition/instantiation conflict.
  src/c4/Processor_Group.hh
  src/c4/Processor_Group.i.hh
  src/c4/Processor_Group_pt.cc
Labels: bug, ready

#432 Enable more tests in the CI systems.
  appveyor.yml
  config/component_macros.cmake
  environment/bashrc/.bashrc
  regression/draco_regression_macros.cmake
  regression/sync_vendors.sh
  src/CMakeLists.txt
Labels: enhancement, needs-review

#433 Minor patch to fix a bug related to Win32 builds.
  README.md
  appveyor.yml
  config/component_macros.cmake
  src/c4/Processor_Group.hh
  src/c4/test/tstTime.cc
Labels: bug, needs-review

#435 Fix a bug in .bashrc; update sample dotfiles.
  environment/bashrc/.bashrc
  environment/bashrc/sample.bash_interactive
  environment/bashrc/sample.bash_profile
  environment/bashrc/sample.bashrc
  environment/elisp/sample.emacs
Labels: dev-env

#437 Add preliminary X3D Draco_Mesh parser.
  src/CMakeLists.txt
  src/mesh/CMakeLists.txt
  src/mesh/Draco_Mesh_Builder.t.hh
  src/mesh/Draco_Mesh_Builder_pt.cc
  src/mesh/Draco_Mesh_Reader.hh
  src/mesh/RTT_Draco_Mesh_Reader.cc
  src/mesh/RTT_Draco_Mesh_Reader.hh
  src/mesh/X3D_Draco_Mesh_Reader.cc
  src/mesh/X3D_Draco_Mesh_Reader.hh
  src/mesh/X3D_Draco_Mesh_Reader.i.hh
  src/mesh/test/CMakeLists.txt
  src/mesh/test/tstDraco_Mesh_Builder.cc
  src/mesh/test/tstX3D_Draco_Mesh_Reader.cc
  src/mesh/test/x3d.mesh.in
Labels: enhancement, ready

#438 Add ability to read X3D boundary files.
  src/mesh/X3D_Draco_Mesh_Reader.cc
  src/mesh/X3D_Draco_Mesh_Reader.hh
  src/mesh/test/tstX3D_Draco_Mesh_Reader.cc
  src/mesh/test/x3d.mesh.bdy1.in
  src/mesh/test/x3d.mesh.bdy2.in
  src/mesh/test/x3d.mesh.bdy3.in
  src/mesh/test/x3d.mesh.bdy4.in
Labels: enhancement, ready

#440 Attempt to use Docker for Travis CI checks.
  .travis-install-dependencies.sh
  .travis-run-tests.sh
  .travis.yml
  CMakeLists.txt
  README.draco
  config/setupMPI.cmake
  config/unix-g++.cmake
  regression/Dockerfile
  regression/travis-run-tests.sh
  src/CMakeLists.txt
  src/VendorChecks/test/tstSuperludist.cc
Labels: enhancement, needs-review

#441 Tweaks to eliminate build warnings for 64-bit builds under VS2017.
  config/ApplicationUnitTest.cmake
  config/component_macros.cmake
  config/setupMPI.cmake
  src/c4/test/tstProcessor_Group.cc
  src/c4/test/tstTime.cc
  src/ds++/Release.hh
  src/rng/test/ut_gsl.c
Labels: bug, needs-review
