Repository lanl/Draco, pull requests merged in 2018-05, with the labels that each got.

#398 Fix a bug in FindCOMPTON.cmake.
  .travis.yml
  config/FindCOMPTON.cmake
  config/vendor_libraries.cmake
  environment/bashrc/.bashrc
Labels: bug

#399 CCS-NET: Update developer environment to use newer tools.
  environment/bashrc/.bashrc_darwin_fe
  environment/bashrc/.bashrc_linux64
  environment/bashrc/.bashrc_toss22
  environment/bashrc/.bashrc_toss3
  environment/bashrc/.bashrc_tt
  regression/ccscs-regress.msub
  regression/check_style.sh
  regression/checkpr.sh
  regression/cts1-regress.msub
  regression/pull_repositories_xf.sh
  regression/push_repositories_xf.sh
  regression/repository_list.sh
  regression/sync_repository.sh
  regression/tt-regress.msub
  regression/update_regression_scripts.sh
  regression/valgrind_suppress.txt
  src/cdi_eospac/Eospac.cc
  src/cdi_eospac/Eospac.hh
  src/cdi_eospac/SesameTables.hh
Labels: enhancement

#400 Load modules 1-by-1 in bash_functions2 version of dracoenv.
  environment/bashrc/bash_functions2.sh
Labels: enhancement, ready

#401 Fix a bad entry in valgrind_suppress.txt.
  config/vendor_libraries.cmake
  regression/valgrind_suppress.txt
Labels: bug, ready

#402 Patch logic used to identify the Fortran compiler flavor.
  config/compilerEnv.cmake
Labels: bug, ready

#403 Fix a bug in sync_repository.sh that prevented PRs from running.
  environment/bashrc/.bashrc_linux64
  regression/ccscs-regress.msub
  regression/sync_repository.sh
Labels: bug

#404 Cleanup some code to eliminate build/run warnings.
  regression/valgrind_suppress.txt
  src/RTT_Format_Reader/RTT_Format_Reader.cc
  src/cdi_eospac/Eospac.cc
Labels: enhancement, needs-review, ready

#406 More GitHub badges
  LICENSE.md
  README.md
  environment/bashrc/.bashrc_slurm
Labels: enhancement, ready

#405 Provide basic support for the flang (LLVM) compiler.
  config/compilerEnv.cmake
  config/unix-flang.cmake
Labels: enhancement, needs-review

#407 Fix bug in Timer::printline_mean
  src/c4/Timer.cc
Labels: bug, ready

#408 Improve robustness of compiler and MPI detection
  CMakeLists.txt
  config/compilerEnv.cmake
  config/dracoVersion.cmake
  config/platform_checks.cmake
  config/setupMPI.cmake
  config/unix-clang.cmake
  config/unix-crayCC.cmake
  config/unix-g++.cmake
  config/unix-intel.cmake
  config/unix-pgi.cmake
  config/unix-xl.cmake
  config/vendor_libraries.cmake
  config/windows-cl.cmake
  regression/tt-job-launch.sh
  src/FortranChecks/f90sub/CMakeLists.txt
Labels: enhancement, needs-review

#409 Fix bug in compilerEnv.cmake wrt MSVC builds.
  README.draco
  config/CMakeAddFortranSubdirectory.cmake
  config/compilerEnv.cmake
Labels: bug, needs-review

#410 Fix broken Jayenne-win32 builds (CMakeAddFortranSubdirectory failures)
  config/compilerEnv.cmake
  config/unix-g++.cmake
Labels: bug, needs-review

#411 Fixes for gitlab style runner
  .codecov.yml
  config/compilerEnv.cmake
  config/dracoVersion.cmake
  config/vendor_libraries.cmake
  regression/check_style.sh
Labels: bug, needs-review
