Repository lanl/Draco, pull requests merged in 2018-10, with the labels that each got.

#490 Ensure csk and ndi are loaded by default on trinity/trinitite.
  environment/bashrc/.bashrc_tt
Labels: bug, dev-env, ready

#488 WIP: Clean up CAFS portion of build system to support x86 and x64.
  config/CMakeAddFortranSubdirectory.cmake
  config/compilerEnv.cmake
  config/setupMPI.cmake
  src/FortranChecks/f90sub/CMakeLists.txt
  src/quadrature/ftest/CMakeLists.txt
Labels: dev-env, enhancement, ready

#489 Improve code coverage of cdi_ipcress by extending tests.
  src/c4/test/tstProcessor_Group.cc
  src/cdi_ipcress/IpcressDataTable.cc
  src/cdi_ipcress/IpcressFile.cc
  src/cdi_ipcress/IpcressFile.t.hh
  src/cdi_ipcress/IpcressInterpreter.cc
  src/cdi_ipcress/IpcressOdfmgOpacity.cc
  src/cdi_ipcress/test/CMakeLists.txt
  src/cdi_ipcress/test/IpcressInterpreter.odf.stdin
  src/cdi_ipcress/test/IpcressInterpreter.stdin
  src/cdi_ipcress/test/Ipcress_Interpreter-Al_BeCu.ipcress.gold
  src/cdi_ipcress/test/Ipcress_Interpreter-odfregression10.ipcress.gold
  src/cdi_ipcress/test/tIpcress_Interpreter.py
Labels: enhancement, ready

#493 Fix build failure on Mac's associated with parse_number_impl
  src/ds++/DracoStrings.cc
  src/ds++/DracoStrings.hh
Labels: bug, ready

#491 Generalize X3D boundary condition specification.
  src/mesh/X3D_Draco_Mesh_Reader.cc
  src/mesh/X3D_Draco_Mesh_Reader.hh
  src/mesh/test/tstX3D_Draco_Mesh_Reader.cc
Labels: enhancement, ready

#495 Improve unit test coverage for quadrature/Level_Symmetric.cc
  src/quadrature/test/quadrature_test.cc
  src/quadrature/test/quadrature_test.hh
  src/quadrature/test/tstLevel_Symmetric.cc
Labels: enhancement, ready

#498 Add unstructured cell type option to Ensight translator.
  src/viz/Ensight_Translator.cc
  src/viz/Ensight_Translator.hh
  src/viz/Ensight_Translator.i.hh
  src/viz/test/CMakeLists.txt
  src/viz/test/cell_data_unstr2d
  src/viz/test/tstEnsight_Translator_Unstructured.cc
  src/viz/test/tstEnsight_Translator_Unstructured.cmake
  src/viz/test/tstEnsight_Translator_Unstructured.py
  src/viz/test/unstr2d_bench/Densities.0001
  src/viz/test/unstr2d_bench/Densities.bin.0001
  src/viz/test/unstr2d_bench/Pressure.0001
  src/viz/test/unstr2d_bench/Pressure.bin.0001
  src/viz/test/unstr2d_bench/Temperatures.0001
  src/viz/test/unstr2d_bench/Temperatures.bin.0001
  src/viz/test/unstr2d_bench/Velocity.0001
  src/viz/test/unstr2d_bench/Velocity.bin.0001
  src/viz/test/unstr2d_bench/geo.0001
  src/viz/test/unstr2d_bench/geo.bin.0001
  src/viz/test/unstr2d_bench/unstr2d_testproblem.case
Labels: enhancement

#494 Move to cmake/3.12.1 on HPC machines.
  environment/bashrc/.bashrc_toss22
  environment/bashrc/.bashrc_toss3
  environment/bashrc/.bashrc_tt
  regression/cts1-regress.msub
  regression/tt-regress.msub
Labels: dev-env, ready

#499 Formalize unstructured cell specification for Ensight.
  src/viz/Ensight_Translator.cc
  src/viz/Ensight_Translator.i.hh
  src/viz/test/unstr2d_bench/Pressure.0001
  src/viz/test/unstr2d_bench/Pressure.bin.0001
  src/viz/test/unstr2d_bench/Velocity.0001
  src/viz/test/unstr2d_bench/Velocity.bin.0001
  src/viz/test/unstr2d_bench/geo.0001
  src/viz/test/unstr2d_bench/geo.bin.0001
Labels: bug

#502 Fix warnings/errors reported in Visual Studio regressions.
  config/CMakeAddFortranSubdirectory.cmake
  src/rng/test/kat_c.c
  src/rng/test/time_serial.h
  src/rng/test/ut_gsl.c
  src/rng/test/ut_uniform.cpp
Labels: bug

#503 Remove extraneous paren in .bash_slurm
  environment/bashrc/.bashrc_slurm
Labels: bug, dev-env

#506 Minor patch to CMakeAddFortranSubdirectory to support Jayenne.
  config/CMakeAddFortranSubdirectory.cmake
Labels: bug

#497 Add a file include capability to Token_Streams.
  src/parser/Console_Token_Stream.cc
  src/parser/Console_Token_Stream.hh
  src/parser/File_Token_Stream.cc
  src/parser/File_Token_Stream.hh
  src/parser/Parallel_File_Token_Stream.cc
  src/parser/Parallel_File_Token_Stream.hh
  src/parser/String_Token_Stream.cc
  src/parser/String_Token_Stream.hh
  src/parser/Text_Token_Stream.cc
  src/parser/Text_Token_Stream.hh
  src/parser/Token_Stream.hh
  src/parser/test/CMakeLists.txt
  src/parser/test/console_test.inp
  src/parser/test/parallel_include_test.inp
  src/parser/test/parallel_included.inp
  src/parser/test/tstConsole_Token_Stream.cc
  src/parser/test/tstFile_Token_Stream.cc
  src/parser/test/tstParallel_File_Token_Stream.cc
  src/parser/test/tstString_Token_Stream.cc
Labels: enhancement

#507 Minor code cleanup to eliminate build warnings from Visual Studio
  src/parser/Expression.cc
  src/parser/test/tstConsole_Token_Stream.cc
  src/parser/test/tstFile_Token_Stream.cc
  src/parser/test/tstParallel_File_Token_Stream.cc
  src/parser/test/tstString_Token_Stream.cc
  src/parser/utilities.cc
Labels: bug

#505 Add more pragmas to suppress warnings found in R123 headers.
  src/rng/test/kat_c.c
  src/rng/test/kat_cpp.cpp
  src/rng/test/time_serial.h
  src/rng/test/ut_Engine.cpp
  src/rng/test/ut_aes.cpp
  src/rng/test/ut_carray.cpp
Labels: bug

#492 Update developer environment for Darwin.
  config/platform_checks.cmake
  config/unix-xl.cmake
  environment/bashrc/.bashrc
  environment/bashrc/.bashrc_darwin_fe
Labels: dev-env

#509 Teach the PR regression system to also build autodoc.
  environment/bashrc/.bashrc_slurm
  regression/ccscs-regress.msub
  regression/checkpr.sh
  regression/sync_autodoc.sh
Labels: dev-env, enhancement, ready

#511 Merge Draco-6_25_0 release back to develop
  CMakeLists.txt
  ChangeLog
  regression/scripts/release_cray.sh
  regression/scripts/release_toss.sh
  src/ds++/Release.cc
Labels: enhancement

#516 Fix a few typos in the release scripts.
  regression/scripts/common.sh
  regression/scripts/release_cray.sh
Labels: bug

#515 Fix DbC bug in Draco_Mesh and update X3D parser.
  src/mesh/Draco_Mesh.cc
  src/mesh/Draco_Mesh.hh
  src/mesh/X3D_Draco_Mesh_Reader.cc
  src/mesh/X3D_Draco_Mesh_Reader.hh
  src/mesh/test/tstDraco_Mesh.cc
  src/mesh/test/tstDraco_Mesh_DD.cc
  src/mesh/test/tstX3D_Draco_Mesh_Reader.cc
Labels: bug

#518 A few more tweaks to the release scripts for draco-6_25_0
  regression/scripts/common.sh
  regression/scripts/release_cray.sh
  regression/scripts/release_toss.sh
Labels: bug, ready

#517 Update regression system to support new Capsaicin projects.
  regression/push_repositories_xf.sh
  regression/repository_list.sh
  regression/update_regression_scripts.sh
Labels: enhancement, ready

#508 A couple of tweaks to fix build/run on Darwin ARM nodes.
  environment/bashrc/.bashrc_darwin_fe
  environment/bashrc/.bashrc_slurm
Labels: bug, dev-env, ready
