Repository lanl/Draco, pull requests merged in 2018-06, with the labels that each got.

#414 Added "ythi", which is like xthi except uses std::thread instead of O…
  src/c4/bin/CMakeLists.txt
  src/c4/bin/ythi.cc
Labels: enhancement, ready

#413 Unstructured mesh prototype
  src/CMakeLists.txt
  src/mesh/CMakeLists.txt
  src/mesh/Draco_Mesh.cc
  src/mesh/Draco_Mesh.hh
  src/mesh/test/CMakeLists.txt
  src/mesh/test/tstDraco_Mesh.cc
Labels: enhancement, needs-work

#418 Minor tweaks to enable new package 'mesh' to build under VS2017.
  src/ds++/CMakeLists.txt
  src/mesh/Draco_Mesh.hh
Labels: bug, needs-review

#419 Dbgopt
  src/parser/Debug_Options.cc
  src/parser/Debug_Options.hh
Labels: enhancement, needs-review

#420 Disable Travis config/build/test builds.
  .travis-install-dependencies.sh
  .travis-run-tests.sh
  .travis.yml
  autodoc/ci-testing.dcc
Labels: bug, dev-env, needs-review

#412 Add a parallel output stream.
  src/c4/ofpstream.cc
  src/c4/ofpstream.hh
  src/c4/opstream.cc
  src/c4/opstream.hh
  src/c4/test/tstofpstream.cc
  src/c4/test/tstopstream.cc
Labels: enhancement, ready

#421 Minor tweaks to the configure process.
  config/FindCOMPTON.cmake
  config/setupMPI.cmake
  environment/bashrc/.bashrc
Labels: dev-env, needs-review

#423 Safe a call to sqrt by wrapping its argument in fabs.
  src/c4/Timer.cc
Labels: bug, ready

#422 Add an Appveyor (win32) build to the CI.
  README.md
  appveyor.yml
  config/windows-cl.cmake
  src/CMakeLists.txt
Labels: enhancement, needs-review

#424 1st Draco_Mesh ghost cell implementation
  src/mesh/Draco_Mesh.cc
  src/mesh/Draco_Mesh.hh
  src/mesh/test/CMakeLists.txt
  src/mesh/test/Test_Mesh_Interface.hh
  src/mesh/test/tstDraco_Mesh.cc
  src/mesh/test/tstDraco_Mesh_DD.cc
Labels: enhancement, ready
