Repository lanl/Draco, pull requests merged in 2019-09, with the labels that each got.

#665 Normalize Planck emission CDF
  src/cdi/CDI.cc
  src/cdi/test/tCDI.cc
Labels: bug

#668 Enable Draco GPU tests
  config/draco-config-install.cmake.in
  config/vendor_libraries.cmake
  src/ds++/Soft_Equivalence.hh
  src/rng/test/CMakeLists.txt
  src/rng/test/kat_cuda.cu
Labels: enhancement

#670 Merge the Draco-7_3_0 release branch back to develop
  CMakeLists.txt
  ChangeLog
  src/ds++/Release.cc
  tools/ats1-env.sh
  tools/ats2-env.sh
  tools/ats2-release.sh
  tools/common.sh
  tools/cray-env.sh
  tools/cts1-env.sh
  tools/cts1-release.sh
  tools/darwin-arm-env.sh
  tools/darwin-power9-env.sh
  tools/darwin-release.sh
  tools/darwin-x86_64-env.sh
  tools/github.api.py
  tools/redmine-release-note-template.txt
  tools/release.msub
  tools/release.sh
Labels: enhancement, ready
