Repository lanl/Draco, pull requests merged in 2019-08, with the labels that each got.

#650 MSVC: Suppress link warning
  config/windows-cl.cmake
  src/cdi_eospac/CMakeLists.txt
  src/cdi_eospac/test/tEospac.cc
  src/compton/CMakeLists.txt
Labels: dev-env, enhancement, ready

#652 Another attempt to suppress MSVC warnings about .dbg files.
  config/component_macros.cmake
  config/windows-cl.cmake
Labels: bug

#653 Shake
  src/parser/Expression.cc
  src/parser/Unit.hh
  src/parser/test/tstExpression.cc
Labels: enhancement, ready

#654 Update docker image used by CI.
  .travis.yml
  tools/Dockerfile
Labels: dev-env, enhancement, ready

#656 WIP: Tweak environments for Capulin support.
  environment/bashrc/.bashrc_cray
Labels: dev-env

#663 Fix broken MSVC (CAFS) build.
  config/component_macros.cmake
  config/windows-cl.cmake
Labels: bug

#664 Provide draco-config-version.cmake when installing.
  config/CMakeLists.txt
Labels: enhancement
