Repository lanl/Draco, pull requests merged in 2019-06, with the labels that each got.

#627 In application_unit_test.py, fix numdiff argument order.
  config/application_unit_test.py
Labels: bug, ready

#632 Update draco-config-install.cmake.in
  config/draco-config-install.cmake.in
Labels: enhancement, ready

#629 Add mscgen and sphinx to the CI docker image.
  .travis.yml
  appveyor.yml
  regression/Dockerfile
  regression/mirrors.yaml
Labels: bug, ready

#634 Add function to query environment vars; class to represent SLURM info…
  src/c4/QueryEnv.hh
  src/c4/test/tstQueryEnv.cc
Labels: enhancement, ready

#631 A few environment tweaks needed before the next release.
  CMakeLists.txt
  config/dracoVersion.cmake
  config/platform_checks.cmake
  config/unix-xl.cmake
  environment/bashrc/.bashrc_cray
  regression/cts1-regress.msub
  regression/scripts/cray-env.sh
  regression/tt-regress.msub
  src/memory/test/CMakeLists.txt
Labels: dev-env, enhancement

#635 Fix setenv/unsetenv for MSVC.
  src/c4/test/tstQueryEnv.cc
Labels: bug

#639 Tweak for Draco-7_2_0
  regression/scripts/ats2-env.sh
  regression/scripts/release_ats2.sh
  src/units/PhysicalConstants.cc
  src/units/PhysicalConstants.hh
Labels: bug

#641 Add environment and release scripts to support Darwin
  environment/bashrc/.bashrc_darwin_fe
  regression/darwin-regress.msub
  regression/scripts/common.sh
  regression/scripts/darwin-env.sh
  regression/scripts/release.msub
  regression/scripts/release_darwin.sh
Labels: enhancement

#644 Fix MSVC build warnings.
  src/mesh/Draco_Mesh_Builder.t.hh
  src/mesh/test/tstDraco_Mesh.cc
Labels: bug

#645 Move draco_setenv to systemcall.hh
  src/c4/test/tstQueryEnv.cc
  src/ds++/SystemCall.hh
Labels: enhancement
