Repository lanl/Draco, pull requests merged in 2019-05, with the labels that each got.

#611 Add support for Capulin and Thunder (LANL ARM systems)
  environment/bashrc/.bashrc
  environment/bashrc/.bashrc_cray
  src/CMakeLists.txt
Labels: enhancement

#613 Fix issue 1268 by documenting and testing report_leaks.
  src/memory/memory.cc
  src/memory/memory.hh
  src/memory/test/tstmemory.cc
Labels: enhancement

#615 Fix build warnings related to superlu_ddefs.h.
  src/VendorChecks/test/CMakeLists.txt
  src/VendorChecks/test/superlu-dist-wrapper.h
  src/VendorChecks/test/tstSuperludist.cc
Labels: bug

#616 Tweak dev env for Darwin
  environment/bashrc/.bashrc_darwin_fe
  regression/darwin-regress.msub
Labels: bug, dev-env

#617 Cleanup warnings/errors reported on CDash.
  environment/bashrc/.bashrc_cray
  regression/push_repositories_xf.sh
  src/VendorChecks/test/CMakeLists.txt
  src/memory/test/CMakeLists.txt
  src/memory/test/tstmemory.cc
Labels: enhancement, ready

#620 Teach DBS to find and use mpirun found at /usr/bin.
  config/setupMPI.cmake
Labels: enhancement

#621 Attempt to fix a static initialization fiasco issue.
  src/units/FundUnit.hh
  src/units/MathConstants.hh
  src/units/PhysicalConstants.hh
  src/units/PhysicalConstantsSI.hh
  src/units/UnitSystem.hh
  src/units/UnitSystemEnums.cc
  src/units/UnitSystemEnums.hh
  src/units/UnitSystemType.cc
  src/units/UnitSystemType.hh
  src/units/test/tstFundUnit.cc
Labels: bug

#619 nGray_Analytic_MultigroupOpacity to Compound_Analytic_MultigroupOpacity
  src/cdi_analytic/Compound_Analytic_MultigroupOpacity.cc
  src/cdi_analytic/Compound_Analytic_MultigroupOpacity.hh
  src/cdi_analytic/Compound_Analytic_Odfmg_Opacity.cc
  src/cdi_analytic/Compound_Analytic_Odfmg_Opacity.hh
  src/cdi_analytic/test/tstAnalytic_Gray_Opacity.cc
  src/cdi_analytic/test/tstAnalytic_Odfmg_Opacity.cc
  src/cdi_analytic/test/tstCompound_Analytic_MultigroupOpacity.cc
Labels: enhancement

#622 More Python 3.0 changes for python ipcress reader
  src/cdi_ipcress/python/demo_read_data.py
  src/cdi_ipcress/python/ipcress_reader.py
Labels: enhancement

#623 Darwin environment updates.
  config/setupMPI.cmake
  environment/bashrc/.bashrc_darwin_fe
  environment/elisp/draco-config-modes.el
  regression/darwin-regress.msub
Labels: dev-env, ready

#624 New docker container for Travis
  .travis.yml
  regression/Dockerfile
  regression/packages.yaml
  regression/travis-run-tests.sh
Labels: enhancement, ready

#625 Loosen tolerance for cdi_ipcress test.
  src/CMakeLists.txt
  src/RTT_Format_Reader/CellDefs.cc
  src/cdi/CDI.hh
  src/cdi_ipcress/test/tIpcress_Interpreter.py
  src/ds++/Assert.hh
  src/parser/utilities.cc
  src/parser/utilities.hh
  src/units/PhysicalConstantsSI.hh
Labels: enhancement

#612 Remove use of deprecated FindPythonInterp
  config/ApplicationUnitTest.cmake
  config/draco-config-install.cmake.in
  config/vendor_libraries.cmake
  src/FortranChecks/CMakeLists.txt
Labels: bug, enhancement, ready

#626 Update dev and regress environment for Cray machines.
  config/setupMPI.cmake
  environment/bashrc/.bashrc_cray
  regression/tt-regress.msub
Labels: bug
