Repository lanl/Draco, pull requests merged in 2019-01, with the labels that each got.

#556 Enable cdi_eospac and memory packages for Win32 builds.
  config/FindEOSPAC.cmake
  config/vendor_libraries.cmake
  src/CMakeLists.txt
  src/cdi_eospac/Eospac.cc
  src/cdi_eospac/SesameTables.cc
  src/cdi_eospac/test/tEospac.cc
  src/cdi_eospac/test/tQueryEospac.cmake
  src/cdi_eospac/test/tQueryEospac.py
  src/memory/memory.hh
  src/memory/test/tstmemory.cc
Labels: enhancement, ready

#555 Modify/Upgrade how the FMA CPP macro works.
  config/autodoc_macros.cmake
  src/ds++/FMA.hh
Labels: enhancement, ready

#557 Fix a module load error
  environment/bashrc/.bashrc_toss3
  environment/bashrc/.bashrc_tt
  src/ds++/FMA.hh
Labels: bug, dev-env

#559 Merge Draco-7_0_0 back to develop
  CMakeLists.txt
  ChangeLog
  regression/pull_repositories_xf.sh
  regression/scripts/cts-env.sh
  regression/scripts/release_cray.sh
  regression/scripts/release_cts.sh
  src/ds++/Release.cc
Labels: enhancement

#562 Setup for trt regressions
  regression/ccscs-job-launch.sh
  regression/ccscs-regress.msub
  regression/ccscs2-crontab
  regression/ccscs3-crontab
  regression/ccscs6-crontab
  regression/cts1-regress.msub
  regression/draco_regression_macros.cmake
  regression/regression-master.sh
  regression/sn-crontab
  regression/tt-crontab
  regression/tt-regress.msub
Labels: enhancement

#566 Simplifying and extending analytic opacity models
  src/cdi_analytic/Analytic_Models.cc
  src/cdi_analytic/Analytic_Models.hh
  src/cdi_analytic/nGray_Analytic_Odfmg_Opacity.cc
  src/cdi_analytic/test/tstAnalytic_Gray_Opacity.cc
Labels: enhancement

#565 Updates to the regression system to support TRT and NPT
  regression/ccscs-job-launch.sh
  regression/ccscs-regress.msub
  regression/checkpr.sh
  regression/cts1-regress.msub
  regression/darwin-regress.msub
  regression/draco_regression_macros.cmake
  regression/sync_repository.sh
  regression/sync_vendors.sh
  regression/tt-regress.msub
Labels: enhancement, ready
