Repository lanl/Draco, pull requests merged in 2019-03, with the labels that each got.

#579 Demo features from issue 318.
  LICENSE.md
  README.md
  autodoc/build_system.dcc.in
  config/ApplicationUnitTest.cmake
  config/apple-clang.cmake
  config/autodoc_macros.cmake
  config/buildEnv.cmake
  config/compilerEnv.cmake
  config/component_macros.cmake
  config/dracoTesting.cmake
  config/generate_dll_declspec.cmake
  config/platform_checks.cmake
  config/setupMPI.cmake
  config/unix-g++.cmake
  config/unix-gfortran.cmake
  config/vendor_libraries.cmake
  config/windows-cl.cmake
  src/ds++/CMakeLists.txt
  src/ds++/Release.cc
  src/ds++/config.h.in
Labels: dev-env, enhancement

#581 Update compile flags for XL.
  config/unix-xl.cmake
  config/unix-xlf.cmake
  src/FortranChecks/test/CMakeLists.txt
Labels: dev-env, ready

#580 Modifications to better support multi-node 'perfbench' and 'newtools' regressions.
  config/platform_checks.cmake
  regression/cts1-job-launch.sh
  regression/cts1-regress.msub
  regression/sn-crontab
  regression/sync_repository.sh
  regression/tt-job-launch.sh
Labels: dev-env, enhancement, ready

#584 Eliminate a compile warning
  src/mesh/Draco_Mesh.cc
  src/mesh/Draco_Mesh.hh
  src/mesh/Draco_Mesh_Builder.hh
  src/mesh/Draco_Mesh_Builder.t.hh
  src/mesh/X3D_Draco_Mesh_Reader.cc
  src/mesh/X3D_Draco_Mesh_Reader.hh
  src/mesh/X3D_Draco_Mesh_Reader.i.hh
Labels: ready

#585 Tweak IPCRESS reader for python 3.0
  src/cdi_ipcress/python/demo_modify_ipcress_file.py
  src/cdi_ipcress/python/demo_read_data.py
  src/cdi_ipcress/python/ipcress_reader.py
  src/cdi_ipcress/python/plot_ipcress_opacity.py
Labels: enhancement, ready

#588 Change authentication method for nightly regression.
  config/vendor_libraries.cmake
  environment/bashrc/.bashrc_slurm
  regression/cts1-regress.msub
  regression/sync_repository.sh
  regression/tt-regress.msub
  regression/update_regression_scripts.sh
Labels: bug

#582 Update regression scripts for darwin (volta-x86).
  config/unix-xl.cmake
  environment/bashrc/.bashrc_darwin_fe
  environment/elisp/draco-config-modes.el
  environment/elisp/psvn.el
  environment/elisp/python-mode.el
  regression/ccscs2-crontab
  regression/checkpr.sh
  regression/darwin-crontab
  regression/darwin-job-launch.sh
  regression/darwin-options.sh
  regression/darwin-regress.msub
  regression/draco_regression_macros.cmake
  regression/regression-master.sh
  regression/scripts/common.sh
  src/VendorChecks/test/tstSuperludist.cc
  src/mesh/test/tstDraco_Mesh.cc
Labels: dev-env, enhancement
