Repository lanl/Draco, pull requests merged in 2019-10, with the labels that each got.

#671 Update bash developer files.
  environment/bashrc/.bashrc
  environment/bashrc/.bashrc_ats2
  environment/bashrc/.bashrc_cray
  environment/bashrc/.bashrc_cts1
  environment/bashrc/.bashrc_linux64
  environment/bashrc/.bashrc_toss3
  environment/bashrc/bash_aliases.sh
  environment/bashrc/bash_functions.sh
  environment/bashrc/bash_functions2.sh
  environment/bashrc/bashrc_slurm
  environment/bashrc/sample.bash_functions
  environment/bashrc/sample.bash_interactive
  environment/bashrc/sample.bash_profile
  environment/bashrc/sample.bashrc
Labels: dev-env, enhancement

#674 Update algorithm for exporting target properties.
  config/component_macros.cmake
  src/rng/CMakeLists.txt
Labels: bug

#675 Minor cleanup of comments, decorators, spelling, etc.
  src/ds++/Release.cc
  src/ds++/ScalarUnitTest.cc
  src/ds++/ScalarUnitTest.hh
  src/ds++/UnitTest.hh
  src/ds++/test/tstRelease.cc
Labels: bug

#676 Two minor tweaks and some formatting fixes.
  src/c4/bin/ythi.cc
  src/c4/test/tstofpstream.cc
  src/diagnostics/draco_info.hh
  src/ds++/Assert.cc
  src/ds++/DracoStrings.cc
  src/ds++/SystemCall.hh
  src/ds++/path.hh
  src/ds++/path_getFilenameComponent.cc
  src/ds++/test/tstAssert.cc
Labels: enhancement, ready

#679 Test new cdash server.
  CTestConfig.cmake
Labels: enhancement

#680 Fix capitalization
  CTestConfig.cmake
Labels: bug

#684 Mark some functions constexpr
  src/ds++/Data_Table.hh
  src/ds++/DracoMath.hh
Labels: enhancement

#682 Provide a mechanism to colorize text.
  LICENSE.md
  config/draco-config-install.cmake.in
  environment/elisp/doxymacs.el
  environment/elisp/draco-config-modes.el
  src/FortranChecks/test/tstDrel.cc
  src/cdi_ipcress/test/tIpcress_Interpreter.py
  src/compton/Compton.cc
  src/compton/Compton.hh
  src/ds++/Assert.cc
  src/ds++/Assert.hh
  src/ds++/CMakeLists.txt
  src/ds++/DracoStrings.hh
  src/ds++/DracoTerminal.cc
  src/ds++/DracoTerminal.hh
  src/ds++/Release.cc
  src/ds++/UnitTest.cc
  src/ds++/terminal/.clang-format
  src/ds++/terminal/LICENSE
  src/ds++/terminal/README.md
  src/ds++/terminal/terminal.h
  src/ds++/terminal/terminal_base.h
  src/ds++/test/tstRelease.cc
  src/ds++/test/tstScalarUnitTest.cc
  src/parser/Text_Token_Stream.cc
Labels: enhancement

#687 Address regression issues reported on Darwin:
  config/FindGrace.cmake
  config/unix-g++.cmake
  config/unix-pgf90.cmake
  environment/bashrc/.bashrc_darwin_fe
  src/ds++/terminal/terminal.h
Labels: bug
