Repository lanl/Draco, pull requests merged in 2019-04, with the labels that each got.

#587 Minor fix: xthi & ythi output formatting
  src/c4/bin/xthi.hh
Labels: enhancement

#594 Attempt to fix style check when target merge is not 'develop'.
  .travis.yml
  regression/check_style.sh
  regression/darwin-regress.msub
  src/c4/test/tstofpstream.cc
Labels: enhancement

#586 Add Analytic Electron-Ion Coupling to CDI
  config/autodoc_macros.cmake
  config/vendor_libraries.cmake
  src/cdi/CDI.cc
  src/cdi/CDI.hh
  src/cdi/EICoupling.hh
  src/cdi/test/CMakeLists.txt
  src/cdi/test/DummyEICoupling.cc
  src/cdi/test/DummyEICoupling.hh
  src/cdi/test/tCDI.cc
  src/cdi/test/tDummyEICoupling.cc
  src/cdi_analytic/Analytic_EICoupling.cc
  src/cdi_analytic/Analytic_EICoupling.hh
  src/cdi_analytic/Analytic_Models.cc
  src/cdi_analytic/Analytic_Models.hh
  src/cdi_analytic/test/tstAnalytic_EICoupling.cc
Labels: enhancement, ready

#591 Fix use of potentially uninitialized vars.
  config/buildEnv.cmake
  config/compilerEnv.cmake
  config/draco-config-install.cmake.in
  config/dracoTesting.cmake
  config/platform_checks.cmake
  config/setupMPI.cmake
  config/vendor_libraries.cmake
  config/windows-cl.cmake
  src/cdi_analytic/Analytic_Gray_Opacity.cc
  src/ds++/Data_Table.hh
Labels: bug

#590 First cut at supporting ATS-2 machines
  config/ApplicationUnitTest.cmake
  config/component_macros.cmake
  config/setupMPI.cmake
  config/unix-xl.cmake
  config/unix-xlf.cmake
  environment/bashrc/.bashrc
  environment/bashrc/.bashrc_ats2
  environment/bashrc/.bashrc_bgq
  regression/scripts/common.sh
  src/mesh/test/tstDraco_Mesh.cc
Labels: enhancement, ready

#600 Add graphic dump reset time, to refine overwrite behavior.
  src/viz/Ensight_Translator.hh
  src/viz/Ensight_Translator.i.hh
  src/viz/test/tstEnsight_Translator.cc
Labels: enhancement, ready

#589 Change the device library to use CUDA runtime API
  config/component_macros.cmake
  config/query_gpu.cu
  config/vendor_libraries.cmake
  src/device/GPU_Device.cc
  src/device/GPU_Device.cmake
  src/device/GPU_Device.hh
  src/device/GPU_Module.cc
  src/device/GPU_Module.hh
  src/device/config.h.in
  src/device/device_cuda.h
  src/device/test/Dual_Call.cu
  src/device/test/Dual_Call.hh
  src/device/test/GPU_Device.cmake
  src/device/test/basic_kernels.cu
  src/device/test/basic_kernels.hh
  src/device/test/gpu_device_info.cu
  src/device/test/gpu_dual_call_test.cu
  src/device/test/gpu_hello_driver_api.cc
  src/device/test/gpu_hello_rt_api.cu
  src/device/test/gpu_hello_rt_api.hh
  src/device/test/gpu_kernel.cu
  src/device/test/vector_add.cu
Labels: enhancement

#592 Feature add atomics
  src/ds++/DracoStrings.hh
  src/ds++/atomics.hh
  src/ds++/test/tstatomics.cc
Labels: enhancement, needs-review

#599 On snow, change gcc640 regression to gcc740.
  config/vendor_libraries.cmake
  environment/bashrc/.bashrc_toss3
  regression/cts1-options.sh
  regression/cts1-regress.msub
  regression/scripts/common.sh
  regression/sn-crontab
  src/lapack_wrap/CMakeLists.txt
Labels: dev-env, enhancement

#607 Teach the build system about mpich.
  config/setupMPI.cmake
Labels: enhancement, ready

#604 Fix errors in CMake CUDA flags and set the NVCC language level to 14
  config/vendor_libraries.cmake
Labels: bug, ready

#597 Minor cleanup
  LICENSE.md
  config/application_unit_test.py
  config/unix-clang.cmake
  config/unix-g++.cmake
  config/unix-ifort.cmake
  environment/bashrc/.bashrc
  environment/bashrc/.bashrc_ats2
  environment/bashrc/sample.bashrc
  regression/draco_regression_macros.cmake
  regression/sync_repository.sh
  src/CMakeLists.txt
  src/cdi_ipcress/autodoc/cdi_ipcress.dcc.in
Labels: enhancement, ready

#606 Don't force DBS settings on clients.
  config/vendor_libraries.cmake
Labels: bug, needs-review, ready

#609 Fix issues that appeared after PR597 was merged
  src/CMakeLists.txt
Labels: bug, ready
