Repository lanl/Draco, pull requests merged in 2019-11, with the labels that each got.

#651 Implement a rudimentary charged-particle data interface in CDI
  src/cdi/CDI.cc
  src/cdi/CDI.hh
  src/cdi/CPCommon.hh
  src/cdi/CPEloss.hh
  src/cdi_analytic/Analytic_CP_Eloss.cc
  src/cdi_analytic/Analytic_CP_Eloss.hh
  src/cdi_analytic/Analytic_Models.cc
  src/cdi_analytic/Analytic_Models.hh
  src/cdi_analytic/test/tstAnalytic_CP_Eloss.cc
Labels: enhancement

#699 More robust pre-commit hooks
  environment/git/pre-commit
Labels: dev-env, ready

#698 Begin posting all regression results to ccstest.lanl.gov.
  CTestConfig.cmake
Labels: ready

#700 Minor cleanup
  LICENSE.md
  config/generate_dll_declspec.cmake
  environment/elisp/cmake-mode.el
  src/c4/gatherv.t.hh
  src/ds++/config.h.in
  src/ds++/test/tstSP.cc
  src/quadrature/Ordinate.cc
  src/units/FundUnit.hh
Labels: enhancement

#701 A constexpr physical units class
  src/units/PhysicalConstexprs.hh
  src/units/test/tstPhysicalConstexprs.cc
Labels: enhancement

#702 Fix static build.
  config/generate_dll_declspec.cmake
  src/c4/CMakeLists.txt
Labels: bug
