Repository lanl/Draco, pull requests merged in 2020-07, with the labels that each got.

#866 Fix broken cmake code introduced in PR 865
  config/draco-config-install.cmake.in
Labels: bug

#869 Provide clang-tidy recommended changes
  environment/bashrc/.bashrc
  src/CMakeLists.txt
  src/cdi_ndi/CMakeLists.txt
  src/cdi_ndi/NDI_AtomicMass.cc
  src/cdi_ndi/NDI_AtomicMass.hh
  src/ds++/Index_Set.hh
  src/linear/gaussj.i.hh
  src/linear/ludcmp.i.hh
  src/linear/qrdcmp.i.hh
  src/linear/test/tstqrdcmp.cc
  src/linear/test/tstqrupdt.cc
  src/linear/test/tstsvdcmp.cc
  src/memory/memory.cc
  src/memory/memory.hh
  src/memory/test/tstmemory.cc
  src/mesh_element/Element_Definition.cc
  src/mesh_element/Element_Definition.hh
  src/mesh_element/test/TestElementDefinition.cc
  src/ode/Function_Traits.hh
  src/ode/quad.i.hh
  src/ode/rkqs.i.hh
  src/ode/test/tstquad.cc
  src/units/PhysicalConstexprs.hh
  src/units/UnitSystemEnums.hh
  src/units/UnitSystemType.cc
  src/units/UnitSystemType.hh
  src/units/test/tstFundUnit.cc
  src/units/test/tstUnitSystem.cc
  src/units/test/tstUnitSystemEnums.cc
  src/units/test/tstUnitSystemType.cc
Labels: enhancement, needs-work

#872 Add two macros for GPU builds
  src/device/config.h.in
Labels: enhancement

#870 Clean up clang-tidy warnings that were missed in #869
  src/CMakeLists.txt
  src/linear/btridag.i.hh
  src/linear/ludcmp.i.hh
  src/linear/ludcmp_pt.cc
  src/linear/svbksb.i.hh
  src/linear/tred2.hh
  src/linear/tred2.i.hh
  src/linear/tred2_pt.cc
  src/ode/CMakeLists.txt
  src/ode/test/CMakeLists.txt
  src/ode/test/tstFunction_Traits.cc
  src/ode/test/tstquad.cc
Labels: bug, ready

#867 Developer environment updates for rzansel
  config/component_macros.cmake
  config/setupMPI.cmake
  config/unix-cuda.cmake
  environment/bashrc/.bashrc_ats2
  src/ds++/Assert.hh
  src/rng/test/CMakeLists.txt
Labels: dev-env, ready

#868 Add a wait_all call to c4 that returns the source rank ID for MPI comms
  src/c4/C4_Functions.hh
  src/c4/C4_MPI.cc
  src/c4/C4_Req.hh
  src/c4/C4_Serial.cc
  src/c4/test/tstsend_is.cc
Labels: enhancement, question

#876 Minor compatibility update for MSVC 2019 16.7.0 Preview 4.0
  src/c4/test/tstsend_is.cc
  src/ds++/config.h.in
Labels: bug, ready

#877 Upgrade super-linter from 2.1.0 to 3.3.1
  .github/workflows/linter.yml
Labels: bug, dev-env

#879 Support cuda/11 for Darwin p9 with XL
  config/unix-cuda.cmake
  config/unix-xl.cmake
  tools/common.sh
Labels: dev-env, enhancement

#881 Fix USE_CUDA=OFF logic so that Cuda is actually disabled.
  config/compilerEnv.cmake
Labels: bug, dev-env

#880 Fix clang-format version issue.
  environment/git/pre-commit-clang-format
Labels: bug, dev-env

#882 Apply clang-tidy transformations to parser component.
  src/CMakeLists.txt
  src/parser/Abstract_Class_Parser.cc
  src/parser/Abstract_Class_Parser.hh
  src/parser/Abstract_Class_Parser.i.hh
  src/parser/Class_Parse_Table.hh
  src/parser/Class_Parser.i.hh
  src/parser/Console_Token_Stream.cc
  src/parser/Console_Token_Stream.hh
  src/parser/Constant_Expression.cc
  src/parser/Constant_Expression.hh
  src/parser/Expression.cc
  src/parser/Expression.hh
  src/parser/File_Token_Stream.cc
  src/parser/File_Token_Stream.hh
  src/parser/Parallel_File_Token_Stream.cc
  src/parser/Parallel_File_Token_Stream.hh
  src/parser/Parse_Table.cc
  src/parser/Parse_Table.hh
  src/parser/String_Token_Stream.cc
  src/parser/String_Token_Stream.hh
  src/parser/Text_Token_Stream.cc
  src/parser/Text_Token_Stream.hh
  src/parser/Token.cc
  src/parser/Token.hh
  src/parser/Token_Equivalence.cc
  src/parser/Token_Stream.cc
  src/parser/Token_Stream.hh
  src/parser/test/tstAbstract_Class_Contextual_Parser.cc
  src/parser/test/tstAbstract_Class_Parser.cc
  src/parser/test/tstClass_Parse_Table.cc
  src/parser/test/tstClass_Parser.cc
  src/parser/test/tstConsole_Token_Stream.cc
  src/parser/test/tstExpression.cc
  src/parser/test/tstFile_Token_Stream.cc
  src/parser/test/tstParallel_File_Token_Stream.cc
  src/parser/test/tstParse_Table.cc
  src/parser/test/tstString_Token_Stream.cc
  src/parser/test/tstToken.cc
  src/parser/test/tstToken_Equivalence.cc
  src/parser/test/tstutilities.cc
  src/parser/utilities.cc
  src/parser/utilities.hh
Labels: enhancement, ready

#883 Apply clang-tidy recommendations in a few more places
  src/cdi_CPEloss/Analytic_CP_Eloss.cc
  src/cdi_eospac/test/tEospac.cc
  src/diagnostics/qt/diWidget.cc
  src/diagnostics/qt/diWidget.hh
  src/diagnostics/qt/main.cc
  src/diagnostics/qt/mainwindow.hh
  src/diagnostics/test/tstTiming.cc
  src/meshReaders/Hex_Mesh_Reader.cc
  src/min/test/tstmrqmin.cc
  src/parser/Parse_Table.hh
  src/parser/test/tstAbstract_Class_Contextual_Parser.cc
  src/parser/test/tstAbstract_Class_Parser.cc
  src/parser/test/tstExpression.cc
  src/roots/test/tstzbrac.cc
  src/roots/test/tstzbrent.cc
Labels: dev-env, ready

#884 Constant analytic stopping power model
  src/cdi_CPEloss/Analytic_Constant_Eloss_Model.hh
  src/cdi_CPEloss/test/tstAnalytic_CP_Eloss.cc
Labels: enhancement

#875 Augment Draco developer environment for CTS-1 and ATS-1.
  environment/bashrc/.bashrc_ats2
  environment/bashrc/.bashrc_cray
  environment/bashrc/.bashrc_cts1
Labels: dev-env

#885 Update darwin p9 environment and spectrum-mpi args.
  config/setupMPI.cmake
  environment/bashrc/.bashrc_darwin_fe
Labels: dev-env, enhancement

#887 Add jerk, sh==shake as unit names in unit parser.
  src/parser/test/tstutilities.cc
  src/parser/test/utilities.inp
  src/parser/utilities.cc
Labels: enhancement, ready

#888 Fix clang-tidy warning in tEospacWithCDI.cc
  src/cdi_eospac/test/tEospacWithCDI.cc
Labels: enhancement
