Repository lanl/Draco, pull requests merged in 2020-10, with the labels that each got.

#917 Comment only changes for 100 col format.
  .github/workflows/linter.yml
  CMakeLists.txt
  config/compilerEnv.cmake
  config/windows-msvc.cmake
  src/cdi/CDI.hh
  src/ds++/Assert.cc
  src/ds++/Assert.hh
Labels: dev-env

#920 Tweak emacs defaults
  environment/elisp/draco-mode.el
Labels: dev-env

#911 Update rng tests to be compatible with Random123 ver 1.13.2.
  environment/bashrc/.bashrc_darwin_fe
  src/rng/CMakeLists.txt
  src/rng/config.h.in
  src/rng/test/CMakeLists.txt
  src/rng/test/kat.h
  src/rng/test/kat_c.c
  src/rng/test/kat_cpp.cpp
  src/rng/test/kat_cuda.cu
  src/rng/test/kat_dev_execute.h
  src/rng/test/kat_main.h
  src/rng/test/rngNxW.h
  src/rng/test/time_initkeyctr.h
  src/rng/test/time_misc.h
  src/rng/test/time_random123.h
  src/rng/test/time_serial.c
  src/rng/test/ut_Engine.cpp
  src/rng/test/ut_Engine.hh
  src/rng/test/ut_M128.cpp
  src/rng/test/ut_aes.cpp
  src/rng/test/ut_ars.c
  src/rng/test/ut_carray.cpp
  src/rng/test/ut_carray.hh
  src/rng/test/ut_uniform.cpp
  src/rng/test/ut_uniform_reference.hpp
  src/rng/test/util.h
  src/rng/test/util_cpu.h
  src/rng/test/util_cuda.h
  src/rng/test/util_demangle.hpp
  src/rng/test/util_expandtpl.h
  src/rng/test/util_m128.h
  src/rng/test/util_print.h
Labels: enhancement

#923 WIP: Add diagnostics to debug issues with openmpi-4.
  config/setupMPI.cmake
  src/c4/ParallelUnitTest.cc
  src/c4/test/tstQuoWrapper.cc
Labels: bug

#924 Clean up build warnings reported by regression
  config/compilerEnv.cmake
  config/dracoVersion.cmake
  config/unix-clang.cmake
  config/unix-g++.cmake
  src/diagnostics/qt/diWidget.cc
  src/rng/test/kat_cpp.cpp
  tools/README
  tools/ats2-env.sh
Labels: enhancement

#925 Remove openmpi debug-daemons option.
  .flake8
  .github/workflows/linter.yml
  config/setupMPI.cmake
Labels: bug

#928 Disable tstQuoWrapper_4 unit test from running under valgrind.
  src/c4/test/CMakeLists.txt
Labels: bug

#929 Fix msvc default settings.
  CMakeSettings.json
  config/CMakeAddFortranSubdirectory.cmake
  config/unix-g++.cmake
Labels: bug, dev-env, ready

#931 Tweak rng tests to support Random123-1.13.2 with LLVM 10.
  config/component_macros.cmake
  src/ds++/Assert.hh
  src/rng/test/CMakeLists.txt
  src/rng/test/kat_c.cc
  src/rng/test/time_initkeyctr.h
  src/rng/test/time_misc.h
  src/rng/test/time_random123.h
  src/rng/test/time_serial.cc
  src/rng/test/util_cpu.h
  src/rng/test/util_print.h
Labels: bug, enhancement

#909 Use supermodules in Draco bashrc setup files.
  .github/workflows/linter.yml
  environment/bashrc/.bashrc
  environment/bashrc/.bashrc_ats2
  environment/bashrc/.bashrc_darwin_fe
Labels: dev-env

#932 Suppress an MSVC warning
  src/rng/test/ut_ars.c
Labels: bug

#936 Apply clang-tidy transformations to 'viz'
  src/CMakeLists.txt
  src/viz/Ensight_Stream.cc
  src/viz/Ensight_Stream.hh
  src/viz/Ensight_Translator.cc
  src/viz/Ensight_Translator.hh
  src/viz/Ensight_Translator.i.hh
  src/viz/Viz_Traits.hh
  src/viz/test/tstEnsight_Stream.cc
  src/viz/test/tstEnsight_Translator.cc
  src/viz/test/tstEnsight_Translator_Unstructured.cc
  src/viz/test/tstViz_Traits.cc
Labels: dev-env, enhancement, ready

#935 100-column-format updates for RTT_Format_Reader
  src/FortranChecks/CMakeLists.txt
  src/FortranChecks/f90sub/CMakeLists.txt
  src/FortranChecks/f90sub/Draco_Test.F90
  src/FortranChecks/f90sub/derived_types.f90
  src/FortranChecks/f90sub/drel.f90
  src/FortranChecks/f90sub/sub1.f90
  src/FortranChecks/fc_derived_type.cc
  src/FortranChecks/test/CMakeLists.txt
  src/FortranChecks/test/cppmain.cc
  src/FortranChecks/test/tstDerivedTypes.cc
  src/FortranChecks/test/tstDrel.cc
  src/RTT_Format_Reader/CMakeLists.txt
  src/RTT_Format_Reader/CellData.cc
  src/RTT_Format_Reader/CellData.hh
  src/RTT_Format_Reader/CellDataIDs.cc
  src/RTT_Format_Reader/CellDataIDs.hh
  src/RTT_Format_Reader/CellDefs.cc
  src/RTT_Format_Reader/CellDefs.hh
  src/RTT_Format_Reader/CellFlags.cc
  src/RTT_Format_Reader/CellFlags.hh
  src/RTT_Format_Reader/Cells.cc
  src/RTT_Format_Reader/Cells.hh
  src/RTT_Format_Reader/Dims.cc
  src/RTT_Format_Reader/Dims.hh
  src/RTT_Format_Reader/Flags.cc
  src/RTT_Format_Reader/Flags.hh
  src/RTT_Format_Reader/Header.cc
  src/RTT_Format_Reader/Header.hh
  src/RTT_Format_Reader/NodeData.cc
  src/RTT_Format_Reader/NodeData.hh
  src/RTT_Format_Reader/NodeDataIDs.cc
  src/RTT_Format_Reader/NodeDataIDs.hh
  src/RTT_Format_Reader/NodeFlags.cc
  src/RTT_Format_Reader/NodeFlags.hh
  src/RTT_Format_Reader/Nodes.cc
  src/RTT_Format_Reader/Nodes.hh
  src/RTT_Format_Reader/RTT_Format_Reader.cc
  src/RTT_Format_Reader/RTT_Format_Reader.hh
  src/RTT_Format_Reader/RTT_Mesh_Reader.cc
  src/RTT_Format_Reader/RTT_Mesh_Reader.hh
  src/RTT_Format_Reader/SideData.cc
  src/RTT_Format_Reader/SideData.hh
  src/RTT_Format_Reader/SideDataIDs.cc
  src/RTT_Format_Reader/SideDataIDs.hh
  src/RTT_Format_Reader/SideFlags.cc
  src/RTT_Format_Reader/SideFlags.hh
  src/RTT_Format_Reader/Sides.cc
  src/RTT_Format_Reader/Sides.hh
  src/RTT_Format_Reader/autodoc/RTT_Format_Reader.dcc.in
  src/RTT_Format_Reader/test/CMakeLists.txt
  src/RTT_Format_Reader/test/TestRTTFormatReader.cc
  src/RTT_Format_Reader/test/TestRTTFormatReader.hh
  src/RTT_Format_Reader/test/TestRTTMeshReader.cc
  src/RTT_Format_Reader/test/TestRTTPolyhedron.cc
Labels: enhancement

#933 Apply clang-tidy fixes to rng component.
  src/CMakeLists.txt
  src/cdi/CDI_Integrate_Rosseland_Planckian_Spectrum.cc
  src/parser/Class_Parser.hh
  src/parser/Class_Parser.i.hh
  src/rng/ChangeLog
  src/rng/Counter_RNG.hh
  src/rng/Halton_Sequence.cc
  src/rng/Halton_Sequence.hh
  src/rng/Halton_Subrandom_Generator.cc
  src/rng/Halton_Subrandom_Generator.hh
  src/rng/LC_Subrandom_Generator.cc
  src/rng/LC_Subrandom_Generator.hh
  src/rng/Sobol_Sequence.cc
  src/rng/Sobol_Sequence.hh
  src/rng/Subrandom_Generator.hh
  src/rng/test/kat_cpp.cpp
  src/rng/test/time_serial.cc
  src/rng/test/tstRnd_Control_Inline.cc
  src/rng/test/ut_M128.cpp
  src/rng/test/ut_carray.cpp
  src/rng/test/ut_uniform.cpp
  src/special_functions/Factorial.i.hh
  src/special_functions/Factorial_pt.cc
Labels: enhancement, ready

#937 Apply clang-tidy recommendations to component 'cdi_analytic'
  src/CMakeLists.txt
  src/cdi/CDI_Integrate_Rosseland_Planckian_Spectrum.cc
  src/cdi_analytic/Analytic_EICoupling.cc
  src/cdi_analytic/Analytic_EICoupling.hh
  src/cdi_analytic/Analytic_EoS.cc
  src/cdi_analytic/Analytic_EoS.hh
  src/cdi_analytic/Analytic_Gray_Opacity.cc
  src/cdi_analytic/Analytic_Gray_Opacity.hh
  src/cdi_analytic/Analytic_Models.hh
  src/cdi_analytic/Analytic_MultigroupOpacity.cc
  src/cdi_analytic/Analytic_MultigroupOpacity.hh
  src/cdi_analytic/Compound_Analytic_MultigroupOpacity.cc
  src/cdi_analytic/Compound_Analytic_MultigroupOpacity.hh
  src/cdi_analytic/Pseudo_Line_Analytic_MultigroupOpacity.cc
  src/cdi_analytic/Pseudo_Line_Analytic_MultigroupOpacity.hh
  src/cdi_analytic/Pseudo_Line_Base.hh
  src/cdi_analytic/test/cdi_analytic_test.hh
  src/cdi_analytic/test/tstAnalytic_EICoupling.cc
  src/cdi_analytic/test/tstAnalytic_EoS.cc
  src/cdi_analytic/test/tstAnalytic_Gray_Opacity.cc
  src/cdi_analytic/test/tstCompound_Analytic_MultigroupOpacity.cc
  src/parser/Class_Parser.i.hh
  src/rng/Counter_RNG.hh
  src/rng/Halton_Sequence.cc
  src/rng/LC_Subrandom_Generator.hh
  src/rng/Subrandom_Generator.hh
  src/rng/test/kat_cpp.cpp
  src/rng/test/ut_M128.cpp
  src/rng/test/ut_carray.cpp
  src/rng/test/ut_uniform.cpp
Labels: dev-env, enhancement, ready

#941 Process ndi_cdi with clang-format at 100 columns
  src/cdi_ndi/CMakeLists.txt
  src/cdi_ndi/NDI_AtomicMass.cc
  src/cdi_ndi/NDI_AtomicMass.hh
  src/cdi_ndi/NDI_Base.cc
  src/cdi_ndi/NDI_Base.hh
  src/cdi_ndi/NDI_TNReaction.cc
  src/cdi_ndi/NDI_TNReaction.hh
  src/cdi_ndi/config.h.in
  src/cdi_ndi/test/CMakeLists.txt
  src/cdi_ndi/test/tstNDI_AtomicMass.cc
  src/cdi_ndi/test/tstNDI_TNReaction.cc
Labels: enhancement, ready

#943 Minor cleanup of HPC bash scripts
  config/query_gpu.cu
  environment/bashrc/.bashrc_cray
  environment/bashrc/bash_aliases.sh
  environment/bashrc/bash_functions.sh
  environment/bashrc/bash_functions2.sh
  environment/bashrc/bashrc_slurm
Labels: dev-env

#942 Proccess cdi_eospac with clang-format for 100-col wrap.
  src/cdi_eospac/ChangeLog
  src/cdi_eospac/Eospac.cc
  src/cdi_eospac/Eospac.hh
  src/cdi_eospac/EospacException.hh
  src/cdi_eospac/QueryEospac.cc
  src/cdi_eospac/SesameTables.cc
  src/cdi_eospac/SesameTables.hh
  src/cdi_eospac/test/tQueryEospac.cmake
  src/cdi_eospac/test/tQueryEospac.py
Labels: dev-env

#944 Convert typedef statements to using statements
  CMakeLists.txt
  src/RTT_Format_Reader/CellData.hh
  src/RTT_Format_Reader/CellDataIDs.hh
  src/RTT_Format_Reader/CellDefs.hh
  src/RTT_Format_Reader/CellFlags.hh
  src/RTT_Format_Reader/Cells.hh
  src/RTT_Format_Reader/Dims.hh
  src/RTT_Format_Reader/Flags.hh
  src/RTT_Format_Reader/Header.hh
  src/RTT_Format_Reader/NodeData.hh
  src/RTT_Format_Reader/NodeDataIDs.hh
  src/RTT_Format_Reader/NodeFlags.hh
  src/RTT_Format_Reader/Nodes.hh
  src/RTT_Format_Reader/RTT_Format_Reader.hh
  src/RTT_Format_Reader/RTT_Mesh_Reader.hh
  src/RTT_Format_Reader/SideData.hh
  src/RTT_Format_Reader/SideDataIDs.hh
  src/RTT_Format_Reader/SideFlags.hh
  src/RTT_Format_Reader/Sides.hh
  src/RTT_Format_Reader/test/TestRTTFormatReader.hh
  src/c4/xthi_cpuset.hh
  src/cdi_analytic/test/tstAnalytic_EICoupling.cc
  src/cdi_analytic/test/tstAnalytic_EoS.cc
  src/mesh/Draco_Mesh.hh
  src/mesh/X3D_Draco_Mesh_Reader.hh
  src/mesh/test/Test_Mesh_Interface.hh
  src/quadrature/Ordinate_Set_Mapper.cc
  src/quadrature/Quadrature.cc
  src/quadrature/Quadrature__parser.hh
  src/quadrature/gauleg.hh
  src/rng/Counter_RNG.hh
  src/rng/test/kat_cpp.cpp
  src/rng/uniform.hpp
  src/special_functions/gaulag.hh
  src/viz/Ensight_Stream.hh
  src/viz/Ensight_Translator.cc
Labels: dev-env

#939 Update all build system files that set compiler flags.
  config/apple-clang.cmake
  config/compilerEnv.cmake
  config/draco-config-install.cmake.in
  config/unix-clang.cmake
  config/unix-crayCC.cmake
  config/unix-crayftn.cmake
  config/unix-cuda.cmake
  config/unix-flang.cmake
  config/unix-g++.cmake
  config/unix-gfortran.cmake
  config/unix-ifort.cmake
  config/unix-intel.cmake
  config/unix-pgf90.cmake
  config/unix-pgi.cmake
  config/unix-xl.cmake
  config/unix-xlf.cmake
  config/windows-cl.cmake
  config/windows-clang.cmake
Labels: dev-env, ready
