Repository lanl/Draco, pull requests merged in 2020-05, with the labels that each got.

#818 Change CMake logic for lib cdi_ndi to ensure upstream code can build when NDI is not found
  src/cdi_ndi/CMakeLists.txt
  src/cdi_ndi/NDI_AtomicMass.cc
  src/cdi_ndi/NDI_Base.cc
  src/cdi_ndi/NDI_Base.hh
  src/cdi_ndi/NDI_TNReaction.cc
  src/cdi_ndi/NDI_TNReaction.hh
  src/cdi_ndi/config.h.in
  src/cdi_ndi/test/CMakeLists.txt
Labels: enhancement, ready

#819 Protect TNReaction constructors in NDI_FOUND to suppress unreachable …
  src/cdi_ndi/NDI_Base.hh
  src/cdi_ndi/NDI_TNReaction.cc
  src/cdi_ndi/NDI_TNReaction.hh
Labels: enhancement, ready

#815 Tweak XL compiler flags.
  config/unix-xl.cmake
  src/c4/test/tstTime.cc
Labels: dev-env, enhancement

#820 Fix bash environment for rzansel.
  environment/bashrc/.bashrc
  environment/bashrc/.bashrc_ats2
  environment/bashrc/bash_functions.sh
Labels: dev-env

#822 Fix a bug in cdi_ndi related to expected data path.
  src/cdi_ndi/CMakeLists.txt
  src/cdi_ndi/NDI_AtomicMass.cc
  src/cdi_ndi/NDI_AtomicMass.hh
  src/cdi_ndi/NDI_Base.cc
  src/cdi_ndi/NDI_Base.hh
  src/cdi_ndi/config.h.in
  src/cdi_ndi/test/tstNDI_AtomicMass.cc
  src/cdi_ndi/test/tstNDI_TNReaction.cc
Labels: bug

#823 Fix informational code concerning MPIEXEC_PREFLAGS.
  src/CMakeLists.txt
  src/c4/config.h.in
  src/diagnostics/draco_info.cc
Labels: bug

#825 Provide some logic cleanup for MSVC-based builds.
  CMakeSettings.json
  config/buildEnv.cmake
  src/cdi_eospac/CMakeLists.txt
  src/compton/CMakeLists.txt
Labels: enhancement

#824 Update to support LLVM version 10.
  appveyor.yml
  environment/bashrc/.bashrc_linux64
  src/ds++/SortPermutation.hh
Labels: bug, ready

#826 Begin supporting IBM XL builds on Darwin
  config/setupMPI.cmake
  config/unix-xl.cmake
  config/unix-xlf.cmake
  environment/bashrc/bashrc_slurm
Labels: dev-env, enhancement

#827 Spectrum-MPI on Darwin works the same as OpenMPI.
  config/setupMPI.cmake
Labels: bug

#829 Fix build warning reported by gcc-9.2.0.
  src/ds++/SortPermutation.hh
Labels: bug

#832 Reorder enumeration of geometry in mesh_element/Geometry.hh
  src/mesh_element/Geometry.hh
Labels: enhancement

#831 Clean up testing environment for rzansel with XL.
  config/setupMPI.cmake
  config/unix-xl.cmake
  environment/bashrc/.bashrc_ats2
  src/quadrature/test/quadrature_test.cc
Labels: bug

#833 Change filename in ofpstream test to be n-rank-dependent
  src/c4/test/tstofpstream.cc
Labels: ready

#834 Check availability of eos data before registering tests.
  src/cdi_eospac/test/CMakeLists.txt
Labels: dev-env

#835 On rzansel, do not use the --pack lrun/jsrun option.
  config/setupMPI.cmake
  environment/bashrc/.bashrc_ats2
Labels: dev-env

#837 Remove CRAY_PE from the build system.
  config/draco-config-install.cmake.in
  config/platform_checks.cmake
  config/setupMPI.cmake
  config/unix-g++.cmake
  config/unix-intel.cmake
  src/CMakeLists.txt
  src/ds++/CMakeLists.txt
Labels: dev-env, enhancement

#836 Spell out that the base type of Geometry is int.
  src/mesh_element/Geometry.hh
Labels: enhancement

#839 Load no-cuda version of trilinos on darwin.
  environment/bashrc/.bashrc_darwin_fe
Labels: dev-env

#838 Minor update for cuda and g++ compiler flags.
  config/unix-cuda.cmake
  config/unix-g++.cmake
  config/unix-gfortran.cmake
Labels: dev-env, enhancement

#840 Update doxygen version in docker image.
  .travis.yml
  tools/Dockerfile
Labels: dev-env

#841 CAFS - Change hardcoded DEBUG to $BUILD_TYPE
  config/CMakeAddFortranSubdirectory.cmake
Labels: bug

#842 Fix test registration for trinitite (perfbench)
  config/buildEnv.cmake
  config/dracoTesting.cmake
  config/platform_checks.cmake
Labels: bug
