Repository lanl/Draco, pull requests merged in 2020-01, with the labels that each got.

#709 Fix inline comments for QuoWrapper.
  src/c4/QuoWrapper.cc
  src/c4/QuoWrapper.hh
Labels: bug

#708 Return uint32_t instead of int.
  src/c4/QueryEnv.hh
Labels: bug, ready

#715 Provide C++2023 feature mdspan, impl. borrowed from Kokkos.
  CTestCustom.cmake
  LICENSE.md
  config/windows-cl.cmake
  src/CMakeLists.txt
  src/ds++/CMakeLists.txt
  src/ds++/test/CMakeLists.txt
  src/experimental/CMakeLists.txt
  src/experimental/__p0009_bits/accessor_basic.hpp
  src/experimental/__p0009_bits/all_type.hpp
  src/experimental/__p0009_bits/array_workaround.hpp
  src/experimental/__p0009_bits/basic_mdspan.hpp
  src/experimental/__p0009_bits/config.hpp
  src/experimental/__p0009_bits/dynamic_extent.hpp
  src/experimental/__p0009_bits/extents.hpp
  src/experimental/__p0009_bits/fixed_layout_impl.hpp
  src/experimental/__p0009_bits/layout_left.hpp
  src/experimental/__p0009_bits/layout_right.hpp
  src/experimental/__p0009_bits/layout_stride.hpp
  src/experimental/__p0009_bits/macros.hpp
  src/experimental/__p0009_bits/mixed_size_storage.hpp
  src/experimental/__p0009_bits/subspan.hpp
  src/experimental/__p0009_bits/trait_backports.hpp
  src/experimental/autodoc/experimental.dcc.in
  src/experimental/mdspan
  src/experimental/test/CMakeLists.txt
  src/experimental/test/tst_mdspan.cc
Labels: enhancement, ready

#713 Merge Draco-7_4_0 back to develop
  CMakeLists.txt
  ChangeLog
  config/unix-xl.cmake
  src/ds++/Release.cc
  tools/ats1-env.sh
  tools/ats2-env.sh
  tools/cray-env.sh
  tools/cts1-env.sh
  tools/darwin-arm-env.sh
  tools/darwin-power9-env.sh
  tools/darwin-x86_64-env.sh
  tools/github.api.py
  tools/release.msub
Labels: enhancement, ready

#719 Fix build warnings issued by LLVM related to illegal symbol names.
  src/compton/config.h.in
  src/diagnostics/config.h.in
  src/experimental/mdspan
Labels: bug

#721 Fix merge conflict that broke the gcov builds
  config/compilerEnv.cmake
Labels: bug

#725 Manual rebase of tabulated stopping power PR #697
  src/CMakeLists.txt
  src/cdi/CDI.cc
  src/cdi/CDI.hh
  src/cdi/CPCommon.hh
  src/cdi/CPEloss.hh
  src/cdi_CPEloss/CMakeLists.txt
  src/cdi_CPEloss/Tabular_CP_Eloss.cc
  src/cdi_CPEloss/Tabular_CP_Eloss.hh
  src/cdi_CPEloss/test/001-H-001
  src/cdi_CPEloss/test/CMakeLists.txt
  src/cdi_CPEloss/test/README
  src/cdi_CPEloss/test/tstTabular_CP_Eloss.cc
  src/cdi_analytic/Analytic_CP_Eloss.cc
  src/cdi_analytic/Analytic_CP_Eloss.hh
  src/cdi_analytic/test/tstAnalytic_CP_Eloss.cc
Labels: enhancement, needs-work

#722 Only print help message related to CrayPE for non-spack builds.
  config/platform_checks.cmake
Labels: bug, ready

#717 Updates to support vs2019 and vcpkg.
  CMakeLists.txt
  CMakeSettings.json
  config/CMakeAddFortranSubdirectory.cmake
  config/compilerEnv.cmake
  config/print_target_properties.cmake
  config/setupMPI.cmake
  config/vendor_libraries.cmake
  config/windows-cl.cmake
  src/FortranChecks/CMakeLists.txt
  src/FortranChecks/f90sub/CMakeLists.txt
  src/FortranChecks/fc_derived_type.cc
  src/FortranChecks/test/CMakeLists.txt
  src/RTT_Format_Reader/CellDataIDs.cc
  src/RTT_Format_Reader/CellFlags.cc
  src/RTT_Format_Reader/Dims.hh
  src/RTT_Format_Reader/Flags.hh
  src/RTT_Format_Reader/Header.cc
  src/c4/C4_Serial.cc
  src/experimental/__p0009_bits/mixed_size_storage.hpp
  src/quadrature/CMakeLists.txt
  src/quadrature/ftest/CMakeLists.txt
  src/rng/Counter_RNG.hh
Labels: enhancement, ready

#727 Fix type conversion errors in GPU device helper
  src/device/GPU_Device.hh
Labels: bug

#728 Ensure that the ythi test uses more than 1 thread to improve code cov
  src/c4/test/CMakeLists.txt
Labels: bug

#729 Improve thoroughness of MSVC CI testing via Appveyor.
  CMakeLists.txt
  appveyor.yml
  config/CMakeAddFortranSubdirectory/config_cafs_proj.cmake.in
  src/CMakeLists.txt
  src/FortranChecks/CMakeLists.txt
  src/FortranChecks/autodoc/FortranChecks.dcc.in
  src/cdi_eospac/CMakeLists.txt
  src/cdi_ipcress/CMakeLists.txt
  src/lapack_wrap/CMakeLists.txt
  src/plot2D/CMakeLists.txt
Labels: enhancement, ready

#730 Make finding the MPI version more robust.
  config/setupMPI.cmake
Labels: bug
