Repository lanl/Draco, pull requests merged in 2020-11, with the labels that each got.

#946 Fix Fortran Flags used by MSVC+CAFS build.
  config/CMakeAddFortranSubdirectory.cmake
  config/unix-gfortran.cmake
  src/c4/fc4/CMakeLists.txt
Labels: bug

#950 Do not use dracoenv functions for ATS2.
  environment/bashrc/.bashrc_ats2
Labels: bug

#947 Remove unused shell script
  environment/bashrc/.bashrc
  environment/bashrc/.bashrc_linux64
Labels: enhancement, ready

#951 Another fix for gfortran based MSVS-CAFS build.
  config/CMakeAddFortranSubdirectory.cmake
  config/compilerEnv.cmake
Labels: bug

#949 Avoid running git commit hooks if git version is old.
  environment/git/pre-commit-clang-format
Labels: dev-env, ready

#953 Test new CI system and associated docker image.
  .travis.yml
  tools/Dockerfile-autodoc.txt
  tools/Dockerfile-basic.txt
  tools/Dockerfile-codecov.txt
  tools/Dockerfile-spack-common-tools.txt
  tools/Dockerfile-spack-gcc.txt
  tools/Dockerfile-spack-llvm.txt
  tools/Dockerfile-spack-setup.txt
  tools/Dockerfile-style-checks.txt
  tools/README.docker
  tools/check_style.sh
  tools/mirrors.yaml
  tools/modules.yaml
  tools/packages.yaml
  tools/travis-run-tests.sh
Labels: dev-env, ready

#956 Provide a build error if C4_MPI.hh is included directly.
  config/doxygen_config.in
  src/c4/C4_MPI.hh
  src/c4/C4_Req.hh
  src/c4/C4_Serial.hh
  src/cdi_CPEloss/Analytic_CP_Eloss.cc
Labels: enhancement

#955 Attempt to enable LLVM-based CI in Travis.
  .travis.yml
  tools/Dockerfile-spack-llvm.txt
  tools/modules.yaml
  tools/travis-run-tests.sh
Labels: dev-env

#960 Make it easier to enable valgrind tests.
  config/autodoc_macros.cmake
  config/compilerEnv.cmake
  config/component_macros.cmake
  config/vendor_libraries.cmake
  src/parser/test/CMakeLists.txt
Labels: dev-env, enhancement, ready

#962 Undo another overzealous linter fix that broke behavior.
  environment/bashrc/bash_functions.sh
Labels: bug, dev-env

#961 Fix device insist issues
  src/ds++/Assert.hh
  src/ds++/test/tstAssert.cc
Labels: bug

#965 Use new module system for CTS-1 machines
  environment/bashrc/.bashrc_cts1
  environment/bin/xfpull
Labels: dev-env
