Repository lanl/Draco, pull requests merged in 2020-02, with the labels that each got.

#731 Update build system to treat CUDA as a first class compiler.
  .gitignore
  CMakeLists.txt
  CMakeSettings.json
  config/CMakeAddFortranSubdirectory.cmake
  config/compilerEnv.cmake
  config/component_macros.cmake
  config/draco-config-install.cmake.in
  config/print_target_properties.cmake
  config/unix-cuda.cmake
  config/vendor_libraries.cmake
  environment/bashrc/.bashrc_darwin_fe
  src/CMakeLists.txt
  src/FortranChecks/CMakeLists.txt
  src/cdi/test/tCDI.cc
  src/device/CMakeLists.txt
  src/device/GPU_Device.cmake
  src/device/config.h.in
  src/device/test/CMakeLists.txt
  src/device/test/GPU_Device.cmake
  src/ds++/Assert.hh
  src/ds++/config.h.in
  src/quadrature/CMakeLists.txt
  src/rng/test/CMakeLists.txt
Labels: enhancement, needs-work

#736 Fix power9 regression.
  config/unix-cuda.cmake
Labels: bug

#735 Updates to support MSVC 2019-based regressions.
  CMakeSettings.json
  config/compilerEnv.cmake
  config/vendor_libraries.cmake
  config/windows-cl.cmake
  src/RTT_Format_Reader/test/CMakeLists.txt
  src/RTT_Format_Reader/test/TestRTTFormatReader.cc
  src/RTT_Format_Reader/test/TestRTTMeshReader.cc
  src/RTT_Format_Reader/test/TestRTTPolyhedron.cc
  src/RTT_Format_Reader/test/rttdef.mesh
  src/RTT_Format_Reader/test/rttpolyhedron.2.mesh
  src/RTT_Format_Reader/test/rttpolyhedron.2o.mesh
  src/RTT_Format_Reader/test/rttpolyhedron.3.mesh
  src/RTT_Format_Reader/test/rttpolyhedron.4.mesh
  src/RTT_Format_Reader/test/rttpolyhedron.mesh
  src/RTT_Format_Reader/test/rttquad.mesh
  src/RTT_Format_Reader/test/rttquad5.mesh
  src/RTT_Format_Reader/test/rttquad9.mesh
  src/compton/test/CMakeLists.txt
  src/compton/test/tCompton.cc
  src/meshReaders/Hex_Mesh_Reader.hh
  src/meshReaders/test/CMakeLists.txt
  src/meshReaders/test/TestHexMeshReader.cc
  src/meshReaders/test/cube.mesh
  src/meshReaders/test/quad.mesh
  src/meshReaders/test/slab.mesh
Labels: enhancement, ready

#733 Cleanup and shorten the cmake configure report.
  config/platform_checks.cmake
  config/string_manip.cmake
  src/CMakeLists.txt
Labels: dev-env, enhancement, ready

#732 Update developer environment (tt)
  .github/PULL_REQUEST_TEMPLATE
  environment/bashrc/.bashrc
  environment/bashrc/.bashrc_cray
  tools/common.sh
Labels: bug, enhancement

#738 Remove deprecated ODFMG interfaces and related code.
  src/cdi/CDI.cc
  src/cdi/CDI.hh
  src/cdi/CDI_collapseOdfmgOpacitiesRosseland.cc
  src/cdi/OdfmgOpacity.hh
  src/cdi/test/CMakeLists.txt
  src/cdi/test/DummyOdfmgOpacity.cc
  src/cdi/test/DummyOdfmgOpacity.hh
  src/cdi/test/tCDI.cc
  src/cdi/test/tDummyOpacity.cc
  src/cdi_analytic/Analytic_Odfmg_Opacity.cc
  src/cdi_analytic/Analytic_Odfmg_Opacity.hh
  src/cdi_analytic/Compound_Analytic_Odfmg_Opacity.cc
  src/cdi_analytic/Compound_Analytic_Odfmg_Opacity.hh
  src/cdi_analytic/Pseudo_Line_Analytic_Odfmg_Opacity.cc
  src/cdi_analytic/Pseudo_Line_Analytic_Odfmg_Opacity.hh
  src/cdi_analytic/test/CMakeLists.txt
  src/cdi_analytic/test/tstAnalytic_Odfmg_Opacity.cc
  src/cdi_ipcress/CMakeLists.txt
  src/cdi_ipcress/IpcressOdfmgOpacity.cc
  src/cdi_ipcress/IpcressOdfmgOpacity.hh
  src/cdi_ipcress/test/CMakeLists.txt
  src/cdi_ipcress/test/ReadOdfIpcressFile.cc
  src/cdi_ipcress/test/tIpcressOdfmgOpacity.cc
Labels: enhancement

#734 NDI wrapper for TN reaction products
  config/FindNDI.cmake
  config/vendor_libraries.cmake
  src/CMakeLists.txt
  src/cdi_ndi/CMakeLists.txt
  src/cdi_ndi/NDI_Base.cc
  src/cdi_ndi/NDI_Base.hh
  src/cdi_ndi/NDI_TN.cc
  src/cdi_ndi/NDI_TN.hh
  src/cdi_ndi/test/CMakeLists.txt
  src/cdi_ndi/test/ndi_data
  src/cdi_ndi/test/tstNDI_TN.cc
Labels: enhancement

#741 Fix spelling errors
  src/cdi_eospac/Eospac.hh
  src/cdi_eospac/EospacException.hh
  src/cdi_eospac/SesameTables.cc
  src/cdi_eospac/SesameTables.hh
Labels: enhancement, ready

#740 Augment unit testing to provide better function coverage.
  src/c4/Compare.cc
  src/c4/Global_Timer.hh
  src/c4/Global_Timer_set_global_activity.cc
  src/c4/ParallelUnitTest.hh
  src/c4/Timer.hh
  src/c4/test/tstBroadcast.cc
  src/c4/test/tstC4_Status.cc
  src/c4/test/tstComm_Dup.cc
  src/c4/test/tstGatherScatter.cc
  src/c4/test/tstGlobalTimer.cc
  src/c4/test/tstParallelUnitTest.cc
  src/c4/test/tstPingPong.cc
  src/c4/test/tstReduction.cc
  src/c4/test/tstSwap.cc
  src/c4/test/tstglobal_containers.cc
  src/c4/test/tstofpstream.cc
  src/c4/test/tstopstream.cc
  src/c4/test/tstsend_is.cc
Labels: enhancement

#739 Provide target to print a gcov-based coverage report
  config/compilerEnv.cmake
  config/platform_checks.cmake
  src/FortranChecks/f90sub/Draco_MPI.F90
  src/FortranChecks/f90sub/Draco_Test.F90
  src/FortranChecks/f90sub/mpi_hw_ftest.f90
  src/FortranChecks/f90sub/sub1.f90
  src/c4/QuoWrapper.cc
  src/ds++/CMakeLists.txt
Labels: dev-env, enhancement

#737 Fix broken codecov logic run by Travis and CodeCov.io
  .travis.yml
  config/compilerEnv.cmake
  tools/spack/lcov/package.py
  tools/travis-run-tests.sh
Labels: bug

#743 Fix dev-env for LANL darwin.
  config/unix-ifort.cmake
  environment/bashrc/.bashrc_darwin_fe
Labels: dev-env, ready

#746 Updates to help the VS2019 build find Eospac.
  config/FindEOSPAC.cmake
  config/compilerEnv.cmake
  config/component_macros.cmake
  config/windows-cl.cmake
Labels: bug

#742 Retire timestep
  README.md
  src/CMakeLists.txt
  src/timestep/CMakeLists.txt
  src/timestep/ChangeLog
  src/timestep/autodoc/timestep.dcc.in
  src/timestep/field_ts_advisor.cc
  src/timestep/field_ts_advisor.hh
  src/timestep/field_ts_advisor.t.hh
  src/timestep/field_ts_advisor_pt.cc
  src/timestep/fixed_ts_advisor.cc
  src/timestep/fixed_ts_advisor.hh
  src/timestep/ratio_ts_advisor.cc
  src/timestep/ratio_ts_advisor.hh
  src/timestep/target_ts_advisor.cc
  src/timestep/target_ts_advisor.hh
  src/timestep/test/CMakeLists.txt
  src/timestep/test/dummy_package.cc
  src/timestep/test/dummy_package.hh
  src/timestep/test/tstTimeStep.cc
  src/timestep/ts_advisor.cc
  src/timestep/ts_advisor.hh
  src/timestep/ts_manager.cc
  src/timestep/ts_manager.hh
Labels: enhancement

#750 Fix DBC mismatch in CDI_NDI
  src/cdi_ndi/NDI_TN.cc
Labels: bug, ready

#749 Fix some build warnings related to vs2019.
  config/compilerEnv.cmake
  src/c4/test/tstReduction.cc
  src/rng/test/ut_M128.cpp
Labels: bug, enhancement, ready
