Repository lanl/Draco, pull requests merged in 2020-04, with the labels that each got.

#787 Enable more gcc debug flags by default.
  config/unix-g++.cmake
  src/CMakeLists.txt
Labels: dev-env, enhancement

#789 Fix minor errors on Apple
  src/c4/xthi_cpuset.hh
  src/cdi_analytic/test/tstCompound_Analytic_MultigroupOpacity.cc
Labels: bug, ready

#788 Update to diagnostics/qt to reflect new cmake behavior.
  config/vendor_libraries.cmake
  environment/bashrc/.bashrc_cray
  environment/bashrc/.bashrc_cts1
  src/diagnostics/CMakeLists.txt
  src/diagnostics/qt/CMakeLists.txt
  src/diagnostics/qt/diWidget.cc
  src/diagnostics/qt/diWidget.hh
  src/diagnostics/qt/main.cc
  src/diagnostics/qt/mainwindow.cc
  src/diagnostics/qt/mainwindow.hh
Labels: bug

#791 Rzansel: point to new spack instance for dev TPLs.
  environment/bashrc/.bashrc_ats2
  src/diagnostics/CMakeLists.txt
Labels: dev-env

#792 Eliminate compile warning from Intel.
  src/diagnostics/qt/CMakeLists.txt
Labels: bug

#790 Remove SuperLU_DIST from Draco.
  LICENSE.md
  config/FindSuperLU_DIST.cmake
  config/vendor_libraries.cmake
  src/VendorChecks/test/CMakeLists.txt
  src/VendorChecks/test/big.rua
  src/VendorChecks/test/superlu-dist-wrapper.h
  src/VendorChecks/test/tstSuperludist.cc
Labels: dev-env

#793 Apply recommended clang-tidy transformations to c4.
  config/component_macros.cmake
  src/CMakeLists.txt
  src/c4/C4_Datatype.hh
  src/c4/C4_MPI.hh
  src/c4/C4_MPI_get_processor_name.cc
  src/c4/C4_Req.cc
  src/c4/C4_Req.hh
  src/c4/C4_Status.hh
  src/c4/Global_Timer.hh
  src/c4/Invert_Comm_Map.hh
  src/c4/ParallelUnitTest.cc
  src/c4/ParallelUnitTest.hh
  src/c4/ParallelUnitTest.i.hh
  src/c4/Processor_Group.hh
  src/c4/Processor_Group.i.hh
  src/c4/Termination_Detector.cc
  src/c4/Termination_Detector.hh
  src/c4/Timer.cc
  src/c4/Timer.hh
  src/c4/gatherv.t.hh
  src/c4/global_containers.i.hh
  src/c4/ofpstream.cc
  src/c4/ofpstream.hh
  src/c4/opstream.cc
  src/c4/opstream.hh
  src/c4/scatterv.t.hh
  src/c4/swap.t.hh
  src/c4/test/tstAbort.cc
  src/c4/test/tstBroadcast.cc
  src/c4/test/tstC4_Req.cc
  src/c4/test/tstC4_Status.cc
  src/c4/test/tstComm_Dup.cc
  src/c4/test/tstCompare.cc
  src/c4/test/tstGatherScatter.cc
  src/c4/test/tstGlobalTimer.cc
  src/c4/test/tstOMP.cc
  src/c4/test/tstQueryEnv.cc
  src/c4/test/tstReduction.cc
  src/c4/test/tstSwap.cc
  src/c4/test/tstTime.cc
  src/c4/test/tstVector_Type.cc
  src/c4/test/tstofpstream.cc
  src/c4/test/tstopstream.cc
  src/c4/test/tstsend_is.cc
Labels: enhancement, ready

#796 Rework the 'covrep' make target (Coverage report with lcov/gcov).
  config/capture_lcov.sh
  config/compilerEnv.cmake
Labels: dev-env, enhancement, ready

#797 Misc clean up after recent PRs.
  CMakeLists.txt
  CTestCustom.cmake
  config/CMakeLists.txt
  config/application_unit_test.py
  config/draco-config-install.cmake.in
  config/generate_dll_declspec.cmake
  config/unix-g++.cmake
  environment/bashrc/sample.bash_profile
  src/c4/C4_MPI.cc
  src/c4/C4_Serial.cc
  src/c4/CMakeLists.txt
  src/c4/Termination_Detector.cc
  src/c4/Timer.cc
  src/c4/Timer.hh
  src/c4/test/CMakeLists.txt
  src/c4/test/tstParallelUnitTest.cc
  src/c4/test/tstParallelUnitTestFailMode.cc
  src/c4/test/tstXthi.py
  src/ds++/CMakeLists.txt
  src/ds++/bin/CMakeLists.txt
  src/ds++/test/test_fpe_trap.py
  src/parser/Console_Token_Stream.cc
  src/rng/uniform.hpp
Labels: enhancement, ready

#798 Fix a build issue related to Qt dll files.
  CMakeSettings.json
  config/component_macros.cmake
  src/diagnostics/qt/CMakeLists.txt
Labels: bug, ready

#803 Re-teach the build system to install eospac and csk dll files.
  src/cdi_eospac/CMakeLists.txt
  src/compton/CMakeLists.txt
Labels: bug

#799 Another tweak to help lcov reporting work for client projects.
  config/CMakeLists.txt
  config/compilerEnv.cmake
Labels: bug, dev-env

#794 Fix some test registration commands to improve ctest robustness.
  .gitignore
  src/c4/test/CMakeLists.txt
  src/cdi_ndi/test/CMakeLists.txt
  src/ds++/test/CMakeLists.txt
  src/parser/test/CMakeLists.txt
Labels: enhancement, ready

#805 Fix build issues related to rzansel with cuda and the covrep target
  CMakeLists.txt
  config/compilerEnv.cmake
  config/unix-cuda.cmake
  src/device/test/Dual_Call.hh
Labels: bug

#806 Installed shell scripts need +X permissions.
  config/CMakeLists.txt
Labels: bug, ready

#808 Fix quo test failure by treating std::thread as upper resource bound
  src/c4/test/tstQuoWrapper.cc
Labels: bug

#809 Add .bashrc for LAP VM
  environment/bashrc/.bashrc
  environment/bashrc/.bashrc_vm
Labels: dev-env, ready

#810 Update docker image with cmake-3.17.0 and more
  .travis.yml
  CMakeLists.txt
  tools/Dockerfile
  tools/spack/packages.yaml
  tools/travis-run-tests.sh
Labels: dev-env

#812 Update darwin bashrc to load cmake 3.17.0.
  environment/bashrc/.bashrc_darwin_fe
Labels: bug, dev-env

#807 Lib_rng's dependency on Random123 headers should transitive
  .gitignore
  CMakeLists.txt
  CMakeSettings.json
  config/buildEnv.cmake
  config/component_macros.cmake
  config/draco-config-install.cmake.in
  config/vendor_libraries.cmake
  src/CMakeLists.txt
  src/ds++/CMakeLists.txt
  src/quadrature/CMakeLists.txt
  src/quadrature/fctest/CMakeLists.txt
  src/quadrature/ftest/CMakeLists.txt
  src/rng/CMakeLists.txt
Labels: bug, ready

#816 Provide a new variable for MPIEXEC_PREFLAGS for PERFBENCH.
  config/setupMPI.cmake
Labels: enhancement, ready
