Repository lanl/Draco, pull requests merged in 2020-06, with the labels that each got.

#843 Merge Draco-7_7_0 back to develop
  CMakeLists.txt
  ChangeLog
  tools/ats1-env.sh
  tools/ats2-env.sh
  tools/common.sh
  tools/cts1-env.sh
  tools/darwin-arm-env.sh
  tools/darwin-power9-env.sh
  tools/darwin-x86_64-env.sh
Labels: enhancement

#852 Minor tweak to dev environment.
  config/vendor_libraries.cmake
  environment/bashrc/.bashrc
Labels: dev-env

#853 Split QueryEnv into Query_Env and SLURM_Task_Info for better reuse.
  config/configureFileOnMake.cmake
  config/dracoVersion.cmake
  src/c4/SLURM_Task_Info.hh
  src/c4/bin/ythi.cc
  src/c4/bin/ythi.hh
  src/c4/test/tstQuoWrapper.cc
  src/c4/test/tstSLURM_Task_Info.cc
  src/ds++/Query_Env.hh
  src/ds++/test/tstQuery_Env.cc
Labels: enhancement

#854 Feature Add Caliper
  config/vendor_libraries.cmake
  src/diagnostics/CMakeLists.txt
  src/diagnostics/Timing.hh
  src/diagnostics/config.h.in
  src/diagnostics/test/tstTiming.cc
Labels: enhancement

#856 Bump cmake version to 3.17.2 on HPC.
  environment/bashrc/.bashrc_cray
  environment/bashrc/.bashrc_cts1
Labels: dev-env

#855 Updates needed for clean autodoc build with doxygen-1.8.17.
  autodoc/CMakeLists.txt
  autodoc/build_system.dcc.in
  autodoc/software_development_policies.dcc
  autodoc/vendors.dcc
  config/autodoc_macros.cmake
  config/configureFileOnMake.cmake
  config/doxygen_config.in
  environment/templates/mainpage.dcc
  src/CMakeLists.txt
  src/RTT_Format_Reader/autodoc/RTT_Format_Reader.dcc.in
  src/cdi/test/DummyEICoupling.cc
  src/cdi/test/DummyEICoupling.hh
  src/cdi_eospac/Eospac.cc
  src/cdi_eospac/Eospac.hh
  src/cdi_ipcress/IpcressFile.cc
  src/cdi_ipcress/IpcressFile.hh
  src/ds++/SystemCall.cc
  src/ds++/SystemCall.hh
  src/ds++/autodoc/ds++.dcc.in
  src/ds++/path.hh
  src/ds++/path_getFilenameComponent.cc
  src/quadrature/autodoc/QuadServices.dcc.in
  src/special_functions/Ylm.cc
Labels: enhancement

#859 Fix timing macros for Draco diagnostics timing case.
  src/diagnostics/Timing.hh
Labels: bug

#861 Add "USE_CUDA" preprocessor definition to config file
  config/component_macros.cmake
  src/device/config.h.in
  src/ds++/Assert.hh
  src/ds++/config.h.in
  src/rng/test/CMakeLists.txt
Labels: dev-env, enhancement

#862 viz :: Prevent cell type duplication for cell data print
  src/viz/Ensight_Translator.i.hh
  src/viz/test/bench_parallel_2/Pressure.0001
  src/viz/test/bench_parallel_2/Pressure.bin.0001
  src/viz/test/bench_parallel_2/Velocity.0001
  src/viz/test/bench_parallel_2/Velocity.bin.0001
  src/viz/test/bench_parallel_4/Pressure.0001
  src/viz/test/bench_parallel_4/Pressure.bin.0001
  src/viz/test/bench_parallel_4/Velocity.0001
  src/viz/test/bench_parallel_4/Velocity.bin.0001
  src/viz/test/tstEnsight_Stream.cc
  src/viz/test/unstr2d_bench_parallel_2/Pressure.0001
  src/viz/test/unstr2d_bench_parallel_2/Pressure.bin.0001
  src/viz/test/unstr2d_bench_parallel_2/Velocity.0001
  src/viz/test/unstr2d_bench_parallel_2/Velocity.bin.0001
  src/viz/test/unstr2d_bench_parallel_4/Pressure.0001
  src/viz/test/unstr2d_bench_parallel_4/Pressure.bin.0001
  src/viz/test/unstr2d_bench_parallel_4/Velocity.0001
  src/viz/test/unstr2d_bench_parallel_4/Velocity.bin.0001
Labels: bug

#864 Minor fix to tstEnsight_Stream
  src/viz/test/tstEnsight_Stream.cc
Labels: bug

#865 DevEnv, build, export improvements for Caliper.
  config/FindCaliper.cmake
  config/draco-config-install.cmake.in
  config/vendor_libraries.cmake
  environment/bashrc/.bashrc_cray
  environment/bashrc/.bashrc_cts1
  src/diagnostics/CMakeLists.txt
Labels: bug

#863 Minor environment cleanup
  config/setupMPI.cmake
  environment/bashrc/.bashrc
  environment/bashrc/.bashrc_cray
  tools/ats1-env.sh
  tools/cts1-env.sh
  tools/release.sh
Labels: dev-env, ready
