Repository lanl/Draco, pull requests merged in 2020-12, with the labels that each got.

#964 Use the Insist_device function in device test code
  src/device/test/Dual_Call.cu
  src/ds++/Assert.hh
Labels: enhancement

#966 More environment and build system updates.
  autodoc/CMakeLists.txt
  config/autodoc_macros.cmake
  config/component_macros.cmake
  config/doxygen_config.in
  config/draco-config-install.cmake.in
  environment/bashrc/.bashrc_ccsnet
  environment/bashrc/.bashrc_cray
  environment/bashrc/.bashrc_cts1
  environment/bashrc/.bashrc_rfta
  environment/bashrc/sample.bash_profile
Labels: dev-env, ready

#967 Remove some dead code
  src/ds++/Assert.hh
Labels: enhancement

#971 Remove debug print.
  src/c4/ParallelUnitTest.cc
Labels: bug

#972 Fix a build warning issued by gcc on ARM and Power9.
  src/compton_tools/cskrw.cc
Labels: bug

#844 WIP: Use NDI to get stopping power data
  config/FindNDI.cmake
  src/cdi/CPEloss.hh
  src/cdi_CPEloss/Analytic_CP_Eloss.hh
  src/cdi_CPEloss/Tabular_CP_Eloss.hh
  src/cdi_CPEloss/test/tstAnalytic_CP_Eloss.cc
  src/cdi_ndi/NDI_Base.cc
  src/cdi_ndi/NDI_Base.hh
  src/cdi_ndi/NDI_CP_Eloss.cc
  src/cdi_ndi/NDI_CP_Eloss.hh
  src/cdi_ndi/NDI_TNReaction.cc
  src/cdi_ndi/NDI_TNReaction.hh
  src/cdi_ndi/test/CMakeLists.txt
  src/cdi_ndi/test/dedx_he4_example
  src/cdi_ndi/test/tstNDI_CP_Eloss.cc
Labels: enhancement

#973 CMAKE: add option to not use QT
  config/vendor_libraries.cmake
Labels: dev-env, enhancement

#974 WIP: Tweak mpirun and compile options for P9 with XL and SMPI.
  config/setupMPI.cmake
  config/unix-xl.cmake
  environment/bashrc/.bashrc_darwin_fe
Labels: dev-env, ready

#975 Fix CI issues related to recent NDI stopping power PR
  src/cdi_ndi/NDI_CP_Eloss.cc
  src/cdi_ndi/NDI_CP_Eloss.hh
Labels: bug, ready

#963 Add dual layouts for Draco_Mesh vertices to local and ghost cells.
  src/c4/C4_Functions.hh
  src/c4/C4_MPI.t.hh
  src/c4/C4_MPI_gather_scatter_pt.cc
  src/c4/C4_Serial.t.hh
  src/c4/gatherv.hh
  src/c4/gatherv.t.hh
  src/c4/gatherv_pt.cc
  src/mesh/Draco_Mesh.cc
  src/mesh/Draco_Mesh.hh
  src/mesh/test/CMakeLists.txt
  src/mesh/test/tstDraco_Mesh.cc
  src/mesh/test/tstDraco_Mesh_DD.cc
Labels: enhancement

#977 Retire plot2D
  .clang-format
  autodoc/build_system.dcc.in
  config/FindGrace.cmake
  config/vendor_libraries.cmake
  src/CMakeLists.txt
  src/plot2D/CMakeLists.txt
  src/plot2D/ChangeLog
  src/plot2D/Colormap.hh
  src/plot2D/LineProps.hh
  src/plot2D/Plot2D.cc
  src/plot2D/Plot2D.hh
  src/plot2D/SetProps.hh
  src/plot2D/SymbolProps.hh
  src/plot2D/autodoc/plot2D.dcc.in
  src/plot2D/config.h.in
  src/plot2D/plot2D_grace.h
  src/plot2D/test/CMakeLists.txt
  src/plot2D/test/bench/bench_plot1.agr
  src/plot2D/test/bench/bench_plot2.agr
  src/plot2D/test/bench/bench_plot3.agr
  src/plot2D/test/bench/bench_plot4.agr
  src/plot2D/test/bench/tstPlot2D.par
  src/plot2D/test/python/tstPlot2D_Diff.py.in
  src/plot2D/test/tstPlot2D.cc
Labels: enhancement

#978 Clang tidy fixes and more.
  src/c4/C4_Functions.hh
  src/c4/C4_MPI.t.hh
  src/c4/C4_MPI_reductions_pt.cc
  src/c4/C4_Serial.t.hh
  src/c4/test/tstReduction.cc
  src/cdi_ndi/NDI_Base.cc
  src/cdi_ndi/NDI_Base.hh
  src/cdi_ndi/NDI_TNReaction.cc
  src/cdi_ndi/NDI_TNReaction.hh
  src/compton_tools/Compton_Native.cc
  src/ds++/DracoStrings.cc
  src/ds++/DracoStrings.hh
  src/ds++/test/tstDracoStrings.cc
Labels: bug

#979 Make global_sum more generic
  environment/bashrc/.bashrc_cray
  src/c4/C4_Functions.hh
  src/c4/C4_MPI.i.hh
  src/c4/C4_MPI.t.hh
  src/c4/C4_MPI_reductions_pt.cc
  src/c4/C4_Serial.hh
  src/c4/C4_Serial.t.hh
Labels: bug, enhancement

#981 Provide an alternate implementation for global_sum
  src/c4/C4_Functions.hh
  src/c4/C4_MPI.i.hh
  src/c4/C4_Serial.hh
Labels: bug, enhancement

#984 Save ndi version to cdi_ndi/config.h
  config/FindNDI.cmake
  src/cdi_ndi/config.h.in
Labels: dev-env, enhancement

#982 Update gcc compile flags
  config/unix-g++.cmake
  src/RTT_Format_Reader/CellDataIDs.cc
  src/RTT_Format_Reader/CellFlags.cc
  src/RTT_Format_Reader/Cells.cc
  src/RTT_Format_Reader/NodeDataIDs.cc
  src/RTT_Format_Reader/NodeFlags.cc
  src/RTT_Format_Reader/Nodes.cc
  src/RTT_Format_Reader/test/TestRTTFormatReader.cc
  src/RTT_Format_Reader/test/TestRTTPolyhedron.cc
  src/c4/scatterv.t.hh
  src/c4/test/tstReduction.cc
  src/c4/test/tstsend_is.cc
  src/cdi_ipcress/IpcressFile.cc
  src/compton_tools/Compton_Native.cc
  src/compton_tools/Compton_Native.hh
  src/ds++/Endian.hh
  src/ds++/Release.cc
  src/ds++/StackTrace.cc
  src/ds++/SystemCall.cc
  src/ds++/path_getFilenameComponent.cc
  src/ds++/terminal/terminal.h
  src/experimental/mdspan
  src/mesh/Draco_Mesh.hh
  src/mesh/RTT_Draco_Mesh_Reader.cc
  src/parser/Class_Parse_Table.hh
  src/quadrature/Sn_Ordinate_Space.cc
  src/quadrature/test/quadrature_test.cc
  src/rng/Counter_RNG.hh
  src/rng/test/kat_cpp.cpp
  src/rng/test/kat_main.h
  src/rng/test/time_serial.cc
  src/rng/test/ut_Engine.cpp
  src/rng/test/ut_M128.cpp
  src/rng/test/ut_carray.cpp
  src/rng/test/ut_uniform.cpp
  src/rng/test/util_cpu.h
  src/rng/test/util_expandtpl.h
  src/rng/test/util_print.h
  src/special_functions/F_eta.cc
  src/viz/Ensight_Translator.i.hh
Labels: bug, ready

#986 Disable NDI stopping powers if NDI version < 2.2.x
  config/FindNDI.cmake
  src/cdi_ndi/NDI_CP_Eloss.cc
  src/cdi_ndi/NDI_CP_Eloss.hh
  src/cdi_ndi/config.h.in
Labels: enhancement, ready

#990 Fix broken logic that sets CMAKE_CONFIGURATION_TYPES.
  config/CMakeLists.txt
  config/draco-config-install.cmake.in
Labels: bug, ready

#988 Use env/cmake variable MPIEXEC_PREFLAGS to add extra mpirun options.
  config/setupMPI.cmake
  tools/travis-run-tests.sh
Labels: dev-env, ready

#992 Make the explicit Counter_RNG constructor available on the GPU
  src/rng/Counter_RNG.hh
Labels: enhancement

#987 Start using a new CDash server.
  CTestConfig.cmake
Labels: dev-env, ready

#993 Update the build system to use new cmake FindLAPACK features.
  config/vendor_libraries.cmake
  src/lapack_wrap/CMakeLists.txt
  src/lapack_wrap/test/CMakeLists.txt
Labels: dev-env, ready

#994 Remove trailing period in config file
  config/apple-clang.cmake
Labels: bug

#995 Bug fix: CMAKE_CONFIGURATION_TYPES should not be set for Makefiles
  config/draco-config-install.cmake.in
Labels: bug

#999 Fix warnings reported by gcc7 and xl16
  config/unix-g++.cmake
  src/CMakeLists.txt
  src/ds++/terminal/terminal.h
  src/experimental/mdspan
  src/rng/Counter_RNG.hh
  src/rng/test/CMakeLists.txt
  src/rng/test/kat_main.h
  src/rng/test/time_serial.cc
  src/rng/test/ut_carray.cpp
  src/rng/test/ut_uniform.cpp
  src/rng/test/util_cpu.h
  src/rng/uniform.hpp
Labels: bug

#997 Fix lapack discovery logic for XLClang.
  config/vendor_libraries.cmake
Labels: bug

#1001 Use CUDA_ARCHITECTURES CMake property.
  config/component_macros.cmake
  config/draco-config-install.cmake.in
  config/query_gpu.cu
  config/unix-cuda.cmake
Labels: bug, dev-env

#1002 Fix a couple of regression/CI issues.
  src/c4/test/CMakeLists.txt
  src/rng/test/CMakeLists.txt
Labels: bug
