Repository lanl/Draco, pull requests merged in 2020-09, with the labels that each got.

#895 Make type conversions explicit when testing large ints
  src/c4/test/tstReduction.cc
Labels: bug

#892 Provide new default dev env for tt and cts1.
  .github/workflows/linter.yml
  environment/bashrc/.bashrc_cray
  environment/bashrc/.bashrc_cts1
  tools/Dockerfile
Labels: dev-env

#897 Minor update to draco-developer bash files.
  environment/bashrc/.bashrc
  environment/bashrc/.bashrc_ccsnet
  environment/bashrc/bash_aliases.sh
  environment/bashrc/bash_functions.sh
Labels: dev-env

#896 Install python-based ipcress file viewer
  src/cdi_ipcress/CMakeLists.txt
  src/cdi_ipcress/python/demo_modify_ipcress_file.py
Labels: enhancement

#899 Minor developer environment updates.
  environment/bashrc/.bashrc_ats2
  environment/bashrc/.bashrc_cts1
  environment/git/pre-commit-f90-format
  environment/lmod/README.lmod
  environment/lmod/sample.lmodrc.lua
  environment/lmod/sample.modulerc.lua
Labels: dev-env

#898 Update cdi_ndi to fetch NDI_GENDIR_PATH at runtime
  src/cdi_ndi/CMakeLists.txt
  src/cdi_ndi/NDI_AtomicMass.cc
  src/cdi_ndi/NDI_AtomicMass.hh
  src/cdi_ndi/NDI_Base.cc
  src/cdi_ndi/NDI_Base.hh
  src/cdi_ndi/config.h.in
  src/cdi_ndi/test/tstNDI_AtomicMass.cc
  src/cdi_ndi/test/tstNDI_TNReaction.cc
  src/ds++/DracoStrings.cc
  src/ds++/DracoStrings.hh
  src/ds++/test/tstDracoStrings.cc
Labels: enhancement

#903 Provide sample lmod module settings files.
  environment/lmod/README.lmod
  environment/lmod/admin.list
Labels: dev-env

#904 Retire package shared_lib
  .clang-format
  README.md
  src/diagnostics/draco_info.cc
  src/shared_lib/Shared_Lib.cc
  src/shared_lib/Shared_Lib.hh
  src/shared_lib/autodoc/shared_lib.dcc.in
  src/shared_lib/config.h.in
  src/shared_lib/dlfcn_support.hh
  src/shared_lib/test/Foo.cc
  src/shared_lib/test/Foo.hh
  src/shared_lib/test/Foo_Base.cc
  src/shared_lib/test/Foo_Base.hh
  src/shared_lib/test/creator_destroyer.cc
  src/shared_lib/test/shared_lib_test.cc
  src/shared_lib/test/shared_lib_test.hh
  src/shared_lib/test/tstShared_Lib.cc
Labels: enhancement

#901 Fix a CrayPrg + spack configuration logic issue
  CMakeLists.txt
  config/platform_checks.cmake
  config/vendor_libraries.cmake
Labels: bug, ready

#908 Provide some updates to the Draco emacs sample scripts.
  environment/elisp/README.elisp
  environment/elisp/draco-config-modes.el
  environment/elisp/draco-global-keys.el
  environment/elisp/draco-mode.el
  environment/elisp/draco-setup.el
  environment/elisp/sample.emacs
Labels: dev-env

#907 WIP: Enable an optional object-library build mode.
  appveyor.yml
  config/CMakeAddFortranSubdirectory/config_cafs_proj.cmake.in
  config/buildEnv.cmake
  config/compilerEnv.cmake
  config/component_macros.cmake
  config/unix-clang.cmake
  config/unix-crayCC.cmake
  config/unix-crayftn.cmake
  config/unix-g++.cmake
  config/unix-gfortran.cmake
  config/unix-ifort.cmake
  config/unix-intel.cmake
  environment/bashrc/.bashrc_cray
  src/CMakeLists.txt
  src/RTT_Format_Reader/CMakeLists.txt
  src/VendorChecks/CMakeLists.txt
  src/c4/CMakeLists.txt
  src/c4/bin/CMakeLists.txt
  src/c4/fc4/CMakeLists.txt
  src/c4/ftest/CMakeLists.txt
  src/cdi/CMakeLists.txt
  src/cdi_CPEloss/CMakeLists.txt
  src/cdi_analytic/CMakeLists.txt
  src/cdi_eospac/CMakeLists.txt
  src/cdi_ipcress/CMakeLists.txt
  src/cdi_ndi/CMakeLists.txt
  src/compton/CMakeLists.txt
  src/device/CMakeLists.txt
  src/diagnostics/CMakeLists.txt
  src/diagnostics/bin/draco_info_main.cc
  src/diagnostics/qt/CMakeLists.txt
  src/ds++/CMakeLists.txt
  src/ds++/bin/CMakeLists.txt
  src/experimental/CMakeLists.txt
  src/fit/CMakeLists.txt
  src/lapack_wrap/CMakeLists.txt
  src/linear/CMakeLists.txt
  src/memory/CMakeLists.txt
  src/mesh/CMakeLists.txt
  src/meshReaders/CMakeLists.txt
  src/mesh_element/CMakeLists.txt
  src/min/CMakeLists.txt
  src/norms/CMakeLists.txt
  src/ode/CMakeLists.txt
  src/parser/Abstract_Class_Parser.i.hh
  src/parser/CMakeLists.txt
  src/plot2D/CMakeLists.txt
  src/quadrature/CMakeLists.txt
  src/quadrature/test/CMakeLists.txt
  src/rng/CMakeLists.txt
  src/roots/CMakeLists.txt
  src/special_functions/CMakeLists.txt
  src/units/CMakeLists.txt
  src/viz/CMakeLists.txt
  src/viz/test/CMakeLists.txt
Labels: enhancement

#910 Fix the clang-tidy regression failure.
  config/compilerEnv.cmake
  config/unix-clang.cmake
  src/VendorChecks/test/tstMetis.cc
Labels: bug

#912 Fix MSVC CLI builds as run by the regression system.
  CMakeSettings.json
  src/rng/test/CMakeLists.txt
  src/rng/test/time_serial.c
  src/rng/test/time_serial.h
  src/rng/test/ut_gsl.c
  src/rng/test/ut_gsl.h
Labels: bug

#913 Merge Draco-7_8_0 back to develop
  CMakeLists.txt
  ChangeLog
  src/diagnostics/draco_info.cc
  src/ds++/Release.cc
  tools/ats1-env.sh
  tools/ats2-env.sh
  tools/common.sh
  tools/cts1-env.sh
  tools/darwin-arm-env.sh
  tools/darwin-power9-env.sh
  tools/darwin-x86_64-env.sh
  tools/release.msub
  tools/release.sh
Labels: enhancement

#916 For Appveyor, force build warnings to be errors
  appveyor.yml
  config/compilerEnv.cmake
  config/windows-cl.cmake
  config/windows-clang.cmake
  config/windows-msvc.cmake
  src/CMakeLists.txt
  src/VendorChecks/test/tstMetis.cc
  src/diagnostics/CMakeLists.txt
  src/ds++/Release.cc
  src/ds++/SystemCall.cc
  src/ds++/config.h.in
  src/ds++/fpe_trap.cc
  src/ds++/terminal/terminal.h
Labels: bug
