Repository lanl/Draco, pull requests merged in 2020-03, with the labels that each got.

#751 More updates for the gcov coverage capability.
  config/compilerEnv.cmake
  src/cdi_analytic/Pseudo_Line_Analytic_MultigroupOpacity.cc
  src/diagnostics/draco_info.cc
  src/diagnostics/draco_info_main.cc
  src/diagnostics/test/CMakeLists.txt
  src/diagnostics/test/tDracoInfo.cmake
  src/diagnostics/test/tDracoInfo.py
Labels: bug, enhancement, ready

#753 Help FindNDI.cmake find the PIC version.
  config/FindNDI.cmake
Labels: bug

#748 Update some files after new components were added to Draco.
  .clang-format
  README.md
  config/component_macros.cmake
Labels: bug, dev-env, ready

#755 Memory
  src/memory/memory.cc
Labels: enhancement, ready

#756 Minor cleanup after debugging session on darwin with GPUs.
  CMakeLists.txt
  config/component_macros.cmake
  environment/bashrc/.bashrc_darwin_fe
Labels: bug, dev-env

#745 Parallel File Reader (ifpstream) to read processors decomposed data.
  src/c4/ifpstream.cc
  src/c4/ifpstream.hh
  src/c4/ofpstream.hh
  src/c4/test/CMakeLists.txt
  src/c4/test/tstifpstream.cc
Labels: enhancement, needs-work

#712 Find draco's TPL via draco-config.cmake.
  config/vendor_libraries.cmake
Labels: bug

#758 Scalar and parallel test cleanup in diagnostic
  config/component_macros.cmake
  src/diagnostics/test/CMakeLists.txt
  src/diagnostics/test/tstruntime_error.cc
Labels: bug, dev-env, ready

#757 Fix %xl compile for ATS-2
  config/setupMPI.cmake
  environment/bashrc/.bashrc_ats2
  src/cdi_CPEloss/Analytic_Eloss_Model.hh
Labels: bug, ready

#754 fix xthi ythi for apple builds
  src/c4/CMakeLists.txt
  src/c4/xthi_cpuset.hh
Labels: enhancement, ready

#760 Merge Draco-7_5_0 branch back to develop
  CMakeLists.txt
  ChangeLog
  environment/bashrc/.bashrc_ats2
  src/ds++/Release.cc
  tools/README
  tools/ats1-env.sh
  tools/ats2-env.sh
  tools/cray-env.sh
  tools/cts1-env.sh
  tools/darwin-arm-env.sh
  tools/darwin-power9-env.sh
  tools/darwin-x86_64-env.sh
  tools/github.api.py
Labels: enhancement

#763 fix tstifpstream
  src/c4/test/tstifpstream.cc
Labels: bug, ready

#761 Add support for NDI atomic mass weights and custom gendir files
  src/cdi_ndi/CMakeLists.txt
  src/cdi_ndi/NDI_AtomicMass.cc
  src/cdi_ndi/NDI_AtomicMass.hh
  src/cdi_ndi/NDI_Base.cc
  src/cdi_ndi/NDI_Base.hh
  src/cdi_ndi/NDI_TNReaction.cc
  src/cdi_ndi/NDI_TNReaction.hh
  src/cdi_ndi/config.h.in
  src/cdi_ndi/test/CMakeLists.txt
  src/cdi_ndi/test/tstNDI_AtomicMass.cc
  src/cdi_ndi/test/tstNDI_TNReaction.cc
  src/units/PhysicalConstexprs.hh
Labels: enhancement

#765 Add more to ignore (Sublime IDE type files)
  .gitignore
Labels: dev-env, ready

#752 Apply recommended clang-tidy transformations.
  config/compilerEnv.cmake
  config/component_macros.cmake
  environment/elisp/draco-mode.el
  src/c4/C4_Functions.hh
  src/c4/C4_MPI.cc
  src/ds++/Data_Table.hh
  src/ds++/Endian.cc
  src/ds++/File_Streams.hh
  src/ds++/Homogeneous_New.hh
  src/ds++/Index_Converter.hh
  src/ds++/Index_Counter.hh
  src/ds++/Index_Set.hh
  src/ds++/Index_Set.t.hh
  src/ds++/Packing_Utils.hh
  src/ds++/Range_Finder.hh
  src/ds++/ScalarUnitTest.hh
  src/ds++/ScalarUnitTest.i.hh
  src/ds++/Soft_Equivalence.hh
  src/ds++/StackTrace.cc
  src/ds++/SystemCall.cc
  src/ds++/SystemCall.hh
  src/ds++/UnitTest.hh
  src/ds++/XGetopt.hh
  src/ds++/fpe_trap.hh
  src/ds++/isSorted.hh
  src/ds++/test/cxx11example_move_semantics.cc
  src/ds++/test/do_exception.cc
  src/ds++/test/tstData_Table.cc
  src/ds++/test/tstEndian.cc
  src/ds++/test/tstIndex_Converter.cc
  src/ds++/test/tstIndex_Counter.cc
  src/ds++/test/tstIndex_Set.cc
  src/ds++/test/tstPacking_Utils.cc
  src/ds++/test/tstRange_finder.cc
  src/ds++/test/tstSP.cc
  src/ds++/test/tstScalarUnitTest.cc
  src/ds++/test/tstSlice.cc
  src/ds++/test/tstSoft_Equiv.cc
  src/ds++/test/tstSortPermutation.cc
  src/ds++/test/tstStackTrace.cc
  src/ds++/test/tstXGetopt.cc
  src/ds++/test/tstdbc.cc
Labels: enhancement, ready

#767 MSVC: Fix link issue related to CSK for Debug builds.
  config/FindEOSPAC.cmake
  config/component_macros.cmake
  config/generate_dll_declspec.cmake
  config/print_target_properties.cmake
Labels: bug, ready

#768 Allow QuoWrapper to work correctly when mpi_init called from F90.
  src/FortranChecks/f90sub/Draco_MPI.F90
  src/c4/C4_MPI.cc
  src/c4/C4_MPI.hh
Labels: enhancement

#766 Improve gcov coverage reporting logic (and other minor changes)
  README.md
  config/compilerEnv.cmake
  config/string_manip.cmake
  config/vendor_libraries.cmake
  src/CMakeLists.txt
  src/ds++/StackTrace.hh
Labels: dev-env, enhancement, ready

#770 Disable build of xthi if OpenMP is not found.
  src/c4/bin/CMakeLists.txt
Labels: bug

#769 Merge Draco-7_6_0 back to develop
  CMakeLists.txt
  ChangeLog
  README.md
  src/c4/test/tstQuoWrapper.cc
  src/ds++/Release.cc
  tools/ats1-env.sh
  tools/ats2-env.sh
  tools/ats2-release.sh
  tools/cray-env.sh
  tools/cts1-env.sh
  tools/darwin-arm-env.sh
  tools/darwin-power9-env.sh
  tools/darwin-x86_64-env.sh
  tools/release.msub
  tools/release.sh
Labels: enhancement

#771 Fix for NDI AMW usage
  src/cdi_ndi/NDI_AtomicMass.cc
Labels: bug

#764 Allow some rng functions to be called on the GPU
  src/CMakeLists.txt
  src/rng/CMakeLists.txt
  src/rng/Counter_RNG.hh
  src/rng/Rnd_Control_Inline.hh
Labels: ready

#772 Fix a couple of clang-tidy warnings.
  src/ds++/Packing_Utils.hh
  src/ds++/Soft_Equivalence.hh
Labels: enhancement, ready

#773 Fix variable name MPIEXEC_PREFLAGS.
  config/ApplicationUnitTest.cmake
  config/component_macros.cmake
  config/setupMPI.cmake
Labels: bug, ready

#774 Help clang-tidy find correct STL headers.
  src/ds++/test/CMakeLists.txt
Labels: bug

#777 Automatically set NDI_ROOT_DIR if NDI is found.
  config/FindNDI.cmake
  src/cdi_ndi/CMakeLists.txt
Labels: bug

#782 Attempt to simplify platform_checks to speed up configure time.
  config/platform_checks.cmake
  src/ds++/config.h.in
Labels: enhancement, ready

#780 Use mdspan
  config/string_manip.cmake
  src/CMakeLists.txt
Labels: enhancement, ready

#781 Synchronize logic for enabling xthi and associated unit test.
  src/c4/bin/CMakeLists.txt
  src/c4/test/CMakeLists.txt
Labels: bug, ready

#776 Turn off separable compilation by default for CUDA libs
  config/component_macros.cmake
Labels: bug

#785 Update Draco dev environment to support KNL on darwin.
  environment/bashrc/.bashrc_darwin_fe
Labels: dev-env, enhancement, ready

#786 Replace deprecated std::pointer_to_unary_function with std::function.
  src/parser/Abstract_Class_Parser.hh
  src/parser/Abstract_Class_Parser.i.hh
Labels: enhancement
