Repository lanl/Draco, pull requests merged in 2021-08, with the labels that each got.

#1095 For X3D mesh generator, provide matid for each cell
  src/mesh/python/x3d_generator.py
Labels: enhancement

#1094 Add error message when CSK data file is not found
  src/compton_tools/Compton_Native.cc
Labels: enhancement

#1096 Adopt LAP SE 1.7 environments on rzansel.
  environment/bashrc/.bashrc_ats2
  src/cdi_eospac/test/CMakeLists.txt
Labels: dev-env

#1097 Switch F90 format checker to fprettify.
  .fprettify.rc
  .github/PULL_REQUEST_TEMPLATE
  environment/git/f90-format.el
  environment/git/install-hooks.sh
  environment/git/pre-commit
  environment/git/pre-commit-f90-format
  environment/git/pre-commit-fprettify
  src/c4/ftest/fc4_test.f90
  src/ds++/path.cc
  tools/check_style.sh
Labels: dev-env

#1098 Add random Voronoi mesh to mesh generators
  src/mesh/python/mesh_types.py
  src/mesh/python/x3d_generator.py
Labels: enhancement

#1099 Fix build warnings reported by gcc on rzansel.
  src/VendorChecks/test/tstParmetis.cc
Labels: enhancement

#1101 Autopep8 py only
  environment/git/pre-commit-autopep8
Labels: bug

#1102 Update URLs to point to re-git.
  CMakeLists.txt
  autodoc/README.autodoc
  autodoc/html/header.html.in
  autodoc/mainpage.dcc.in
  config/ApplicationUnitTest.cmake
  config/draco-config-install.cmake.in
  src/c4/test/CMakeLists.txt
  src/rng/uniform.hpp
  tools/darwin-arm-env.sh
  tools/darwin-power9-env.sh
Labels: dev-env, ready

#1103 Vor2d mesh faces fix
  src/mesh/python/README.md
  src/mesh/python/mesh_types.py
  src/mesh/python/x3d_plotter.py
Labels: enhancement

#1104 Provide basic environment for ATS-4.
  config/unix-clang.cmake
  environment/bashrc/.bashrc_ats4
Labels: dev-env

#1105 Provide git-hook that updates copyright block automagically.
  environment/git/install-hooks.sh
  environment/git/pre-commit
  environment/git/pre-commit-copyright
  tools/check_style.sh
Labels: dev-env

#1107 Use softer adjustment for start date for Copyright block.
  environment/git/pre-commit-copyright
  tools/check_style.sh
Labels: dev-env

#1106 Enhance opstream by allowing output to a specified ostream.
  src/c4/opstream.cc
  src/c4/opstream.hh
  src/ds++/dbc.hh
  src/ds++/dbc.i.hh
Labels: enhancement, ready

#1108 Provide a couple of fixes for XL on power9
  config/compilerEnv.cmake
  config/unix-xl.cmake
Labels: dev-env

#1051 Add quick_index class for rapid spatial data access
  src/kde/kde.cc
  src/kde/kde.hh
  src/kde/kde.i.hh
  src/kde/quick_index.cc
  src/kde/quick_index.hh
  src/kde/test/CMakeLists.txt
  src/kde/test/tstkde.cc
  src/kde/test/tstquick_index.cc
  src/viz/Ensight_Translator.cc
Labels: enhancement

#1112 Add region output, with all the cells, to x3d_generator.py.
  src/mesh/python/x3d_generator.py
Labels: enhancement

#1111 Tweak flags used by gcc/g++
  config/unix-g++.cmake
  src/CMakeLists.txt
Labels: dev-env

#1113 Fix static builds after PR1051 was merged
  src/kde/kde.i.hh
Labels: bug

#1109 Make basic CDI functions constexpr
  src/cdi/CDI.cc
  src/cdi/CDI.hh
  src/cdi/CDI_Integrate_Rosseland_Planckian_Spectrum.cc
  src/cdi/CDI_integratePlanckSpectrum.cc
  src/cdi/CDI_integrateRosselandSpectrum.cc
  src/cdi/CMakeLists.txt
  src/cdi/test/tCDI.cc
  src/cdi_analytic/Pseudo_Line_Analytic_MultigroupOpacity.cc
  src/compton_tools/cskrw.cc
Labels: enhancement

#1116 Fix a bug in pre-commit-copyright and other shell script fixes.
  environment/bashrc/bash_functions.sh
  environment/git/pre-commit-copyright
  tools/check_style.sh
Labels: dev-env

#1117 make origin and target write size match in the mpi_put call
  src/kde/quick_index.cc
  src/kde/quick_index.hh
Labels: bug

#1118 Another fix for the copyright pre-commit-hook
  environment/git/pre-commit-copyright
  tools/check_style.sh
Labels: dev-env

#1119 Bounds check
  src/mesh/X3D_Draco_Mesh_Reader.cc
Labels: enhancement

#1114 Add option to generate arbitrary rectangular (prism) regions.
  src/mesh/python/README.md
  src/mesh/python/x3d_generator.py
Labels: enhancement

#1120 Begin using environment lapse/1.8.0-xl on ATS-2.
  environment/bashrc/.bashrc_ats2
Labels: dev-env

#1121 Another copyright date fix.
  environment/git/pre-commit-copyright
  src/ds++/Assert.cc
  src/ds++/Assert.hh
  tools/check_style.sh
Labels: dev-env

#1122 Use -g instead of -G in standard CUDA flags
  config/unix-cuda.cmake
Labels: bug, dev-env
