Repository lanl/Draco, pull requests merged in 2021-02, with the labels that each got.

#1021 Add support for cce/11.
  CMakeLists.txt
  config/unix-clang.cmake
  config/vendor_libraries.cmake
  src/CMakeLists.txt
  src/c4/fc4/Draco_MPI.F90
Labels: dev-env

#1022 Fix a build issue that prevents MPI from being found for LLVM Debug
  config/vendor_libraries.cmake
Labels: bug

#1023 WIP: Address warnings reported by the appveyour CI.
  appveyor.yml
Labels: bug

#1025 Fix NDI DEDX error in density spacing tolerance
  src/cdi_ndi/NDI_CP_Eloss.cc
Labels: bug

#1024 Extend policy for CDI integrations
  src/cdi/CDI.cc
  src/cdi/CDI.hh
  src/cdi/test/tCDI.cc
Labels: enhancement

#1027 WIP: Update release scripts related to Darwin.
  tools/README
  tools/common.sh
  tools/darwin-arm-env.sh
  tools/darwin-power9-env.sh
  tools/darwin-x86_64-env.sh
Labels: dev-env

#1026 Planck corner case
  src/cdi/CDI.cc
  src/cdi/test/tCDI.cc
Labels: enhancement

#1028 Disable -traceback for CrayPrgEnv to eliminate link warning.
  config/unix-ifort.cmake
Labels: bug

#1029 Hack to work around OpenMPI error 'mkdir unable to create dir".
  config/component_macros.cmake
  config/setupMPI.cmake
Labels: bug

#1030 Force configure to fail if USE_CUDA=ON but no cuda is available.
  CMakeLists.txt
  config/compilerEnv.cmake
Labels: bug

#1032 Here is another try at providing a mca orte_tmpdir_base hack
  config/component_macros.cmake
Labels: bug

#1033 Provide support for Capulin (ARM with cce toolchain).
  config/compilerEnv.cmake
  config/component_macros.cmake
  config/platform_checks.cmake
  config/setupMPI.cmake
  config/unix-clang.cmake
  environment/bashrc/.bashrc_cray
  src/c4/test/tstBroadcast.cc
  src/c4/test/tstReduction.cc
  src/c4/test/tstsend_is.cc
  src/ds++/CMakeLists.txt
  src/ds++/config.h.in
Labels: dev-env, enhancement
