Repository lanl/Draco, pull requests merged in 2021-07, with the labels that each got.

#1083 Fix broken Appveyor CI
  appveyor.yml
Labels: bug

#1081 Add and calculate coordinate container for off-rank neighbor nodes.
  src/c4/C4_MPI_gather_scatter_pt.cc
  src/c4/gatherv_pt.cc
  src/c4/test/tstGatherScatter.cc
  src/mesh/Draco_Mesh.cc
  src/mesh/Draco_Mesh.hh
  src/mesh/test/tstDraco_Mesh_DD.cc
Labels: enhancement

#1085 Tweak some slurm alias commands.
  environment/bashrc/bash_functions.sh
  environment/bashrc/bashrc_slurm
Labels: dev-env, enhancement

#1086 X3d 3d ssfile
  src/mesh/X3D_Draco_Mesh_Reader.cc
  src/mesh/test/tstX3D_Draco_Mesh_Reader.cc
Labels: bug, ready

#1087 Use FMA in Planck integration
  src/cdi/CDI.cc
  src/cdi/CDI.hh
Labels: enhancement, needs-review

#1090 Add preliminary framework for generating X3D (and eventually RTT) mesh files.
  src/mesh/python/mesh_types.py
  src/mesh/python/x3d_generator.py
  src/mesh/test/x3d.mesh.bdy3.in
  src/mesh/test/x3d.mesh.bdy4.in
  src/mesh/test/x3d.mesh.in
Labels: enhancement

#1089 Standardize t.hh vs i.hh filenames
  src/c4/Functors.hh
  src/c4/global_containers.hh
  src/c4/global_containers.t.hh
  src/c4/global_containers_pt.cc
  src/c4/test/tstglobal_containers.cc
  src/cdi_CPEloss/Analytic_Eloss_Model.hh
  src/cdi_ipcress/IpcressFile.cc
  src/ds++/DracoMath.hh
  src/ds++/Index_Set.hh
  src/ds++/Index_Set.i.hh
  src/ds++/Soft_Equivalence.hh
  src/ds++/dbc.hh
  src/ds++/dbc_pt.cc
  src/fit/svdfit.i.hh
  src/fit/test/tstsvdfit.cc
  src/linear/btridag.hh
  src/linear/btridag.t.hh
  src/linear/btridag_pt.cc
  src/linear/gaussj.t.hh
  src/linear/gaussj_pt.cc
  src/linear/qr_unpack.t.hh
  src/linear/qr_unpack_pt.cc
  src/linear/qrdcmp.t.hh
  src/linear/qrdcmp_pt.cc
  src/linear/qrupdt.t.hh
  src/linear/qrupdt_pt.cc
  src/linear/svbksb.t.hh
  src/linear/svbksb_pt.cc
  src/linear/svdcmp.t.hh
  src/linear/svdcmp_pt.cc
  src/linear/tqli.t.hh
  src/linear/tqli_pt.cc
  src/linear/tred2.t.hh
  src/linear/tred2_pt.cc
  src/min/mrqmin.t.hh
  src/min/mrqmin_pt.cc
  src/norms/L2norm.hh
  src/norms/L2norm.i.hh
  src/norms/L2norm_pt.cc
  src/norms/norm.hh
  src/norms/test/tstL2norm.cc
  src/roots/cubic1.t.hh
  src/roots/cubic1_pt.cc
  src/special_functions/Factorial.t.hh
  src/special_functions/Factorial_pt.cc
Labels: bug, ready

#1091 Add 3D orthogonal structure mesh type for mesh generators.
  src/mesh/python/README.md
  src/mesh/python/mesh_types.py
  src/mesh/python/x3d_generator.py
  src/mesh/test/tstX3D_Draco_Mesh_Reader.cc
  src/mesh/test/x3d.mesh3d_1cell.bdy1.in
  src/mesh/test/x3d.mesh3d_1cell.bdy2.in
  src/mesh/test/x3d.mesh3d_1cell.bdy3.in
  src/mesh/test/x3d.mesh3d_1cell.bdy4.in
  src/mesh/test/x3d.mesh3d_1cell.bdy5.in
  src/mesh/test/x3d.mesh3d_1cell.bdy6.in
  src/mesh/test/x3d.mesh3d_1cell.in
Labels: enhancement

#1092 Add test of constructing a simple 3D Draco_Mesh object.
  src/mesh/test/tstX3D_Draco_Mesh_Reader.cc
Labels: enhancement

#1093 Add logic for setting DRACO_ROUNDOFF_MODE for FMA CPP macro.
  .github/PULL_REQUEST_TEMPLATE
  config/buildEnv.cmake
  config/draco-config-install.cmake.in
  config/unix-intelllvm.cmake
  src/ds++/config.h.in
  tools/draco-cmake-opts.sh
Labels: enhancement
