Repository lanl/Draco, pull requests merged in 2021-03, with the labels that each got.

#1035 Provide flake8 fixes for 4 files.
  src/cdi_ipcress/python/demo_modify_ipcress_file.py
  src/cdi_ipcress/python/demo_read_data.py
  src/cdi_ipcress/python/ipcress_reader.py
  src/cdi_ipcress/python/plot_ipcress_opacity.py
Labels: dev-env

#1034 Memory
  src/memory/memory.cc
  src/memory/memory.hh
  src/memory/test/tstmemory.cc
Labels: enhancement

#1037 Update draco environment scripts for ccscs[45].
  config/windows-msvc.cmake
  environment/bashrc/.bashrc
  environment/bashrc/.bashrc_ccsnet
  src/mesh/Draco_Mesh_Builder.t.hh
Labels: enhancement

#1040 Provide work arounds for cmake-3.19 on Cray PEs.
  config/buildEnv.cmake
  environment/bin/xfpull
Labels: bug

#1041 Add optional languages interrogation to draco-config.cmake
  config/draco-config-install.cmake.in
  environment/bashrc/.bashrc_darwin_fe
Labels: dev-env, enhancement

#1042 Update default developer environments.
  environment/bashrc/.bashrc_ats2
  environment/bashrc/.bashrc_ccsnet
  environment/bashrc/.bashrc_cts1
  environment/bashrc/.bashrc_rfta
  environment/bashrc/bashrc_slurm
Labels: dev-env

#1044 Use '--exclusive' srun option on all Cray machines.
  .github/workflows/linter.yml
  config/component_macros.cmake
  config/setupMPI.cmake
  environment/bashrc/.bashrc
  environment/bashrc/.bashrc_cray
  environment/bashrc/bashrc_slurm
  src/diagnostics/qt/CMakeLists.txt
Labels: dev-env

#1045 Fix INTERNAL variable state logic.
  config/component_macros.cmake
Labels: bug
