Repository lanl/Draco, pull requests merged in 2021-06, with the labels that each got.

#1069 Remove constexpr square root call in CDI
  src/cdi/CDI.hh
Labels: bug

#1070 WIP: Attempt to replace Travis with GitHub Actions
  .github/workflows/ci-autodoc.yml
  .github/workflows/ci-clang-tidy.yml
  .github/workflows/ci-gcc-mpi.yml
  .github/workflows/ci-gcc-scalar.yml
  .github/workflows/ci-llvm-mpi.yml
  .github/workflows/ci-style-check.yml
  .travis.yml
  tools/check_style.sh
  tools/travis-run-tests.sh
Labels: dev-env

#998 Provide a mechanism for querying and printing system load.
  src/c4/test/tstOMP.cc
  src/ds++/SystemCall.hh
Labels: enhancement, needs-review, ready

#1073 For Toss3 machines,register tests using srun.
  config/setupMPI.cmake
  src/c4/SLURM_Task_Info.hh
  src/c4/test/tstQuoWrapper.cc
Labels: bug, dev-env

#1074 Fix gcc-based build on ATS-2 and add preliminary env for new machine.
  config/setupMPI.cmake
  environment/bashrc/.bashrc
  environment/bashrc/.bashrc_ats4
Labels: bug, dev-env

#1075 Suppress a gcc warning related to -O3 -g
  config/unix-g++.cmake
Labels: bug, dev-env

#1077 Provide Kent's README.md for parser.
  .github/workflows/linter.yml
  .markdown-lint.json
  src/parser/README.md
Labels: enhancement

#1078 WIP: Add neighboring node indices to dual layouts in Draco_Mesh
  src/mesh/Draco_Mesh.cc
  src/mesh/Draco_Mesh.hh
  src/mesh/test/tstDraco_Mesh.cc
  src/mesh/test/tstDraco_Mesh_DD.cc
Labels: enhancement

#1079 Merge Draco-7_11_0 back to develop
  CMakeLists.txt
  ChangeLog
  src/ds++/Release.cc
  tools/ats1-env.sh
  tools/ats2-env.sh
  tools/cray-env.sh
  tools/cts1-env.sh
  tools/darwin-arm-env.sh
  tools/darwin-power9-env.sh
  tools/darwin-x86_64-env.sh
Labels: enhancement

#1080 Update badges
  README.md
Labels: bug, dev-env
