Repository lanl/Draco, pull requests merged in 2021-09, with the labels that each got.

#1124 Replace use of WIN32 CPP macro with _MSC_VER
  src/c4/C4_MPI.cc
  src/c4/C4_Serial.cc
  src/c4/C4_sys_times.h
  src/c4/Timer.cc
  src/c4/Timer.hh
  src/c4/test/tstTime.cc
  src/c4/xthi_cpuset.hh
  src/ds++/DracoMath.hh
  src/ds++/DracoStrings.cc
  src/ds++/DracoStrings.hh
  src/ds++/StackTrace.cc
  src/ds++/SystemCall.cc
  src/ds++/SystemCall.hh
  src/ds++/path.hh
  src/ds++/path_getFilenameComponent.cc
  src/ds++/test/tstPath.cc
  src/ds++/test/tstdbc.cc
  src/parser/test/tstToken.cc
Labels: dev-env

#1125 Fix overlapping theta boundary in spherical KDE reconstructions
  src/kde/quick_index.cc
Labels: bug

#1127 Update CI scripts based on improvements made in a client project.
  environment/git/pre-commit-copyright
  tools/check_style.sh
Labels: dev-env

#1126 Force lapack use when xlc++.
  config/vendor_libraries.cmake
Labels: bug

#983 Explore the impact of using scoped enum for mesh_element Geometry.
  config/compilerEnv.cmake
  src/RTT_Format_Reader/CellData.cc
  src/mesh/Draco_Mesh.cc
  src/mesh/Draco_Mesh.hh
  src/mesh/Draco_Mesh_Builder.t.hh
  src/mesh/test/tstDraco_Mesh_Builder.cc
  src/mesh_element/Geometry.hh
  src/parser/test/tstutilities.cc
  src/parser/utilities.cc
  src/quadrature/Galerkin_Ordinate_Space.cc
  src/quadrature/Octant_Quadrature.cc
  src/quadrature/Ordinate_Set.cc
  src/quadrature/Ordinate_Set_Factory.cc
  src/quadrature/Ordinate_Space.cc
  src/quadrature/Quadrature.cc
  src/quadrature/Sn_Ordinate_Space.cc
  src/quadrature/test/quadrature_test.cc
  src/quadrature/test/tstOrdinate_Set_Mapper.cc
Labels: enhancement, question

#1130 Expand scope of proxy-on/off.
  environment/bashrc/.bashrc
  environment/bashrc/bash_functions.sh
Labels: dev-env

#1131 Limit number of threads spawned for tstOMP and tstatomics
  src/c4/test/tstOMP.cc
  src/ds++/test/tstatomics.cc
Labels: dev-env

#1132 Cleanup in Abstract_Class_Parser
  config/compilerEnv.cmake
  config/doxygen_config.in
  src/parser/Abstract_Class_Parser.cc
  src/parser/Abstract_Class_Parser.hh
  src/parser/Abstract_Class_Parser.i.hh
  src/parser/Contextual_Parse_Functor.hh
Labels: enhancement, dev-env

#1133 Provide skylake-based env on Darwin.
  environment/bashrc/.bashrc_darwin_fe
Labels: dev-env

#1134 Begin supporting nvcc+xl on darwin P9.
  config/unix-cuda.cmake
Labels: bug, dev-env

#1135 Add CUDA flags to draco_info report
  environment/git/pre-commit-copyright
  src/cdi/test/tCDI.cc
  src/cdi_ipcress/test/cdi_ipcress_test.hh
  src/diagnostics/draco_info.cc
  src/diagnostics/draco_info.hh
  src/ds++/Release.cc
  src/ds++/config.h.in
  src/parser/Abstract_Class_Parser.i.hh
  src/parser/Contextual_Parse_Functor.hh
  tools/check_style.sh
Labels: enhancement

#1137 Adopt LAP SE 1.8 for default develop env on CTS-1 and ATS-1
  config/unix-clang.cmake
  environment/bashrc/.bashrc_cray
  environment/bashrc/.bashrc_cts1
  src/ds++/StackTrace.hh
Labels: dev-env

#1140 Fix bad logic that prevented -fp-model=precise from being used.
  config/unix-clang.cmake
Labels: bug, dev-env
