Repository lanl/Draco, pull requests merged in 2021-01, with the labels that each got.

#1003 Fix bug in DRACO_SHARED_LIBS CPP macro saved to config.h
  config/compilerEnv.cmake
Labels: bug, ready

#996 Allow environment sets via add_[scalar|parallel]_test macro.
  config/component_macros.cmake
  src/parser/test/CMakeLists.txt
Labels: dev-env, enhancement

#1004 Fix plot_ipcress_opacity.py to work with python@3.5+
  src/cdi_ipcress/python/plot_ipcress_opacity.py
Labels: bug

#1005 Ensure installed python programs have the exec bit set.
  src/cdi_ipcress/CMakeLists.txt
  src/compton_tools/CMakeLists.txt
Labels: bug

#1007 Updates for github.api.py.
  environment/elisp/draco-mode.el
  tools/github.api.py
Labels: dev-env, enhancement

#1008 Ofpstream
  src/c4/ofpstream.cc
  src/c4/test/tstofpstream.cc
Labels: bug

#1010 Merge Draco-7_9_0 back into develop
  CMakeLists.txt
  ChangeLog
  README.md
  src/ds++/Release.cc
  tools/ats1-env.sh
  tools/ats2-env.sh
  tools/common.sh
  tools/cts1-env.sh
Labels: enhancement

#1011 rzansel: Tweak SMPI's lrun options for tests that use MPI+OpenMP.
  config/setupMPI.cmake
Labels: bug, ready

#1012 Fix warnings reported by Intel ifort 19.1.3.
  src/c4/fc4/Draco_MPI.F90
Labels: bug

#1013 Updates to default elisp files and templates.
  environment/elisp/Makefile
  environment/elisp/README.elisp
  environment/elisp/doxymacs.el
  environment/elisp/draco-config-modes.el
  environment/elisp/draco-setup.el
  environment/elisp/sample.emacs
Labels: dev-env, ready

#1014 Add global MPI_LAND c4 operation for boolean-type scalars.
  src/c4/C4_Functions.hh
  src/c4/C4_MPI.t.hh
  src/c4/C4_MPI_reductions_pt.cc
  src/c4/C4_Serial.t.hh
  src/c4/test/tstReduction.cc
Labels: enhancement

#1015 Bump Darwin environment to gcc9 (x64 nodes)
  environment/bashrc/.bashrc_darwin_fe
Labels: dev-env

#1017 Update release scripts for +gpu builds.
  tools/ats2-env.sh
  tools/ats2-release.sh
  tools/common.sh
  tools/release.msub
Labels: dev-env

#1016 Provide a flake8 pre-commit hook.
  environment/git/install-hooks.sh
  environment/git/pre-commit
  environment/git/pre-commit-f90-format
  environment/git/pre-commit-flake8
Labels: dev-env

#1018 More cleanup of elisp scripts + make bashrc more robust.
  environment/bashrc/.bashrc
  environment/elisp/ChangeLog
  environment/elisp/doc/README.elisp
  environment/elisp/draco-config-modes.el
  environment/elisp/draco-mode.el
  environment/elisp/draco-setup.el
Labels: dev-env

#1019 Patch up module environments on ATS-2 (and elisp)
  environment/bashrc/.bashrc_ats2
  environment/elisp/draco-config-modes.el
  environment/elisp/draco-setup.el
Labels: dev-env

#1020 Default to power9-gcc930-smpi env and use --bind-to none
  config/setupMPI.cmake
  environment/bashrc/.bashrc_darwin_fe
Labels: bug
